<?php

namespace Anibalealvarezs\Projectbuilder\Database\Seeders;

use Anibalealvarezs\Projectbuilder\Models\PbCity as City;
use Anibalealvarezs\Projectbuilder\Models\PbCountry;
use Illuminate\Database\Seeder;

class PbCitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if ($city = City::first()) {
            if (!$city->country_id) {
                City::query()->delete();
            }
        }
        // Default Cities
        City::upsert([
            ['name' => json_encode(['en' => 'Kabul']), 'country_id' => PbCountry::findByCode('AF')->id],
            ['name' => json_encode(['en' => 'Mariehamn']), 'country_id' => PbCountry::findByCode('AX')->id],
            ['name' => json_encode(['en' => 'Tirana']), 'country_id' => PbCountry::findByCode('AL')->id],
            ['name' => json_encode(['en' => 'Argel']), 'country_id' => PbCountry::findByCode('DZ')->id],
            ['name' => json_encode(['en' => 'Pago Pago']), 'country_id' => PbCountry::findByCode('AS')->id],
            ['name' => json_encode(['en' => 'Andorra la Vieja']), 'country_id' => PbCountry::findByCode('AD')->id],
            ['name' => json_encode(['en' => 'Luanda']), 'country_id' => PbCountry::findByCode('AO')->id],
            ['name' => json_encode(['en' => 'Saint John’s']), 'country_id' => PbCountry::findByCode('AG')->id],
            ['name' => json_encode(['en' => 'Buenos Aires']), 'country_id' => PbCountry::findByCode('AR')->id],
            ['name' => json_encode(['en' => 'Ereván']), 'country_id' => PbCountry::findByCode('AM')->id],
            ['name' => json_encode(['en' => 'Camberra']), 'country_id' => PbCountry::findByCode('AU')->id],
            ['name' => json_encode(['en' => 'Viena']), 'country_id' => PbCountry::findByCode('AT')->id],
            ['name' => json_encode(['en' => 'Bakú']), 'country_id' => PbCountry::findByCode('AZ')->id],
            ['name' => json_encode(['en' => 'Manama']), 'country_id' => PbCountry::findByCode('BH')->id],
            ['name' => json_encode(['en' => 'Daca']), 'country_id' => PbCountry::findByCode('BD')->id],
            ['name' => json_encode(['en' => 'Bridgetown']), 'country_id' => PbCountry::findByCode('BB')->id],
            ['name' => json_encode(['en' => 'Minsk']), 'country_id' => PbCountry::findByCode('BY')->id],
            ['name' => json_encode(['en' => 'Bruselas']), 'country_id' => PbCountry::findByCode('BE')->id],
            ['name' => json_encode(['en' => 'Belmopán']), 'country_id' => PbCountry::findByCode('BZ')->id],
            ['name' => json_encode(['en' => 'Porto Novo & Cotonú']), 'country_id' => PbCountry::findByCode('BJ')->id],
            ['name' => json_encode(['en' => 'Timbu']), 'country_id' => PbCountry::findByCode('BT')->id],
            ['name' => json_encode(['en' => 'La Paz']), 'country_id' => PbCountry::findByCode('BO')->id],
            ['name' => json_encode(['en' => 'Sarajevo']), 'country_id' => PbCountry::findByCode('BA')->id],
            ['name' => json_encode(['en' => 'Gaborone']), 'country_id' => PbCountry::findByCode('BW')->id],
            ['name' => json_encode(['en' => 'Brasilia']), 'country_id' => PbCountry::findByCode('BR')->id],
            ['name' => json_encode(['en' => 'Bandar Seri Begawan']), 'country_id' => PbCountry::findByCode('BN')->id],
            ['name' => json_encode(['en' => 'Sofía']), 'country_id' => PbCountry::findByCode('BG')->id],
            ['name' => json_encode(['en' => 'Uagadugú']), 'country_id' => PbCountry::findByCode('BF')->id],
            ['name' => json_encode(['en' => 'Buyumbura']), 'country_id' => PbCountry::findByCode('BI')->id],
            ['name' => json_encode(['en' => 'Nom Pen']), 'country_id' => PbCountry::findByCode('KH')->id],
            ['name' => json_encode(['en' => 'Yaundé']), 'country_id' => PbCountry::findByCode('CM')->id],
            ['name' => json_encode(['en' => 'Ottawa']), 'country_id' => PbCountry::findByCode('CA')->id],
            ['name' => json_encode(['en' => 'Praia']), 'country_id' => PbCountry::findByCode('CV')->id],
            ['name' => json_encode(['en' => 'Bangui']), 'country_id' => PbCountry::findByCode('CF')->id],
            ['name' => json_encode(['en' => 'Yamena']), 'country_id' => PbCountry::findByCode('TD')->id],
            ['name' => json_encode(['en' => 'Santiago de Chile']), 'country_id' => PbCountry::findByCode('CL')->id],
            ['name' => json_encode(['en' => 'Beijing']), 'country_id' => PbCountry::findByCode('CN')->id],
            ['name' => json_encode(['en' => 'Bogotá']), 'country_id' => PbCountry::findByCode('CO')->id],
            ['name' => json_encode(['en' => 'Moroni']), 'country_id' => PbCountry::findByCode('KM')->id],
            ['name' => json_encode(['en' => 'San José']), 'country_id' => PbCountry::findByCode('CR')->id],
            ['name' => json_encode(['en' => 'Yamusukro']), 'country_id' => PbCountry::findByCode('CI')->id],
            ['name' => json_encode(['en' => 'Zagreb']), 'country_id' => PbCountry::findByCode('HR')->id],
            ['name' => json_encode(['en' => 'Nicosia']), 'country_id' => PbCountry::findByCode('CY')->id],
            ['name' => json_encode(['en' => 'Praga']), 'country_id' => PbCountry::findByCode('CZ')->id],
            ['name' => json_encode(['en' => 'Kinsasa']), 'country_id' => PbCountry::findByCode('CD')->id],
            ['name' => json_encode(['en' => 'Copenhague']), 'country_id' => PbCountry::findByCode('DK')->id],
            ['name' => json_encode(['en' => 'Djibouti']), 'country_id' => PbCountry::findByCode('DJ')->id],
            ['name' => json_encode(['en' => 'Roseau']), 'country_id' => PbCountry::findByCode('DM')->id],
            ['name' => json_encode(['en' => 'Santo Domingo']), 'country_id' => PbCountry::findByCode('DO')->id],
            ['name' => json_encode(['en' => 'Quito']), 'country_id' => PbCountry::findByCode('EC')->id],
            ['name' => json_encode(['en' => 'Cairo']), 'country_id' => PbCountry::findByCode('EG')->id],
            ['name' => json_encode(['en' => 'San Salvador']), 'country_id' => PbCountry::findByCode('SV')->id],
            ['name' => json_encode(['en' => 'Malabo']), 'country_id' => PbCountry::findByCode('GQ')->id],
            ['name' => json_encode(['en' => 'Asmara']), 'country_id' => PbCountry::findByCode('ER')->id],
            ['name' => json_encode(['en' => 'Tallin']), 'country_id' => PbCountry::findByCode('EE')->id],
            ['name' => json_encode(['en' => 'Adís Abeba']), 'country_id' => PbCountry::findByCode('ET')->id],
            ['name' => json_encode(['en' => 'Suva']), 'country_id' => PbCountry::findByCode('FJ')->id],
            ['name' => json_encode(['en' => 'Helsinki']), 'country_id' => PbCountry::findByCode('FI')->id],
            ['name' => json_encode(['en' => 'Paris']), 'country_id' => PbCountry::findByCode('FR')->id],
            ['name' => json_encode(['en' => 'Libreville']), 'country_id' => PbCountry::findByCode('GA')->id],
            ['name' => json_encode(['en' => 'Tiflis']), 'country_id' => PbCountry::findByCode('GE')->id],
            ['name' => json_encode(['en' => 'Berlin']), 'country_id' => PbCountry::findByCode('DE')->id],
            ['name' => json_encode(['en' => 'Acra']), 'country_id' => PbCountry::findByCode('GH')->id],
            ['name' => json_encode(['en' => 'Atenas']), 'country_id' => PbCountry::findByCode('GR')->id],
            ['name' => json_encode(['en' => 'Saint George']), 'country_id' => PbCountry::findByCode('GD')->id],
            ['name' => json_encode(['en' => 'Ciudad de Guatemala']), 'country_id' => PbCountry::findByCode('GT')->id],
            ['name' => json_encode(['en' => 'Conakri']), 'country_id' => PbCountry::findByCode('GN')->id],
            ['name' => json_encode(['en' => 'Bissau']), 'country_id' => PbCountry::findByCode('GW')->id],
            ['name' => json_encode(['en' => 'Georgetown']), 'country_id' => PbCountry::findByCode('GY')->id],
            ['name' => json_encode(['en' => 'Port-au-Prince']), 'country_id' => PbCountry::findByCode('HT')->id],
            ['name' => json_encode(['en' => 'Tegucigalpa']), 'country_id' => PbCountry::findByCode('HN')->id],
            ['name' => json_encode(['en' => 'Budapest']), 'country_id' => PbCountry::findByCode('HU')->id],
            ['name' => json_encode(['en' => 'Reikiavik']), 'country_id' => PbCountry::findByCode('IS')->id],
            ['name' => json_encode(['en' => 'Nueva Delhi']), 'country_id' => PbCountry::findByCode('IN')->id],
            ['name' => json_encode(['en' => 'Yakarta']), 'country_id' => PbCountry::findByCode('ID')->id],
            ['name' => json_encode(['en' => 'Bagdad']), 'country_id' => PbCountry::findByCode('IQ')->id],
            ['name' => json_encode(['en' => 'Dublin']), 'country_id' => PbCountry::findByCode('IE')->id],
            ['name' => json_encode(['en' => 'Jerusalem']), 'country_id' => PbCountry::findByCode('IL')->id],
            ['name' => json_encode(['en' => 'Roma']), 'country_id' => PbCountry::findByCode('IT')->id],
            ['name' => json_encode(['en' => 'Kingston']), 'country_id' => PbCountry::findByCode('JM')->id],
            ['name' => json_encode(['en' => 'Tokyo']), 'country_id' => PbCountry::findByCode('JP')->id],
            ['name' => json_encode(['en' => 'Amman']), 'country_id' => PbCountry::findByCode('JO')->id],
            ['name' => json_encode(['en' => 'Astana']), 'country_id' => PbCountry::findByCode('KZ')->id],
            ['name' => json_encode(['en' => 'Nairobi']), 'country_id' => PbCountry::findByCode('KE')->id],
            ['name' => json_encode(['en' => 'Tarawa']), 'country_id' => PbCountry::findByCode('KI')->id],
            ['name' => json_encode(['en' => 'Pristina']), 'country_id' => PbCountry::findByCode('XK')->id],
            ['name' => json_encode(['en' => 'Kuwait']), 'country_id' => PbCountry::findByCode('KW')->id],
            ['name' => json_encode(['en' => 'Biskek']), 'country_id' => PbCountry::findByCode('KG')->id],
            ['name' => json_encode(['en' => 'Vientiane']), 'country_id' => PbCountry::findByCode('LA')->id],
            ['name' => json_encode(['en' => 'Riga']), 'country_id' => PbCountry::findByCode('LV')->id],
            ['name' => json_encode(['en' => 'Beirut']), 'country_id' => PbCountry::findByCode('LB')->id],
            ['name' => json_encode(['en' => 'Maseru']), 'country_id' => PbCountry::findByCode('LS')->id],
            ['name' => json_encode(['en' => 'Monrovia']), 'country_id' => PbCountry::findByCode('LR')->id],
            ['name' => json_encode(['en' => 'Tripoli']), 'country_id' => PbCountry::findByCode('LY')->id],
            ['name' => json_encode(['en' => 'Vaduz']), 'country_id' => PbCountry::findByCode('LI')->id],
            ['name' => json_encode(['en' => 'Vilna']), 'country_id' => PbCountry::findByCode('LT')->id],
            ['name' => json_encode(['en' => 'Luxembourg']), 'country_id' => PbCountry::findByCode('LU')->id],
            ['name' => json_encode(['en' => 'Skopje']), 'country_id' => PbCountry::findByCode('MK')->id],
            ['name' => json_encode(['en' => 'Antananarivo']), 'country_id' => PbCountry::findByCode('MG')->id],
            ['name' => json_encode(['en' => 'Lilongwe']), 'country_id' => PbCountry::findByCode('MW')->id],
            ['name' => json_encode(['en' => 'Kuala Lumpur']), 'country_id' => PbCountry::findByCode('MY')->id],
            ['name' => json_encode(['en' => 'Malé']), 'country_id' => PbCountry::findByCode('MV')->id],
            ['name' => json_encode(['en' => 'Bamako']), 'country_id' => PbCountry::findByCode('ML')->id],
            ['name' => json_encode(['en' => 'Valletta']), 'country_id' => PbCountry::findByCode('MT')->id],
            ['name' => json_encode(['en' => 'Majuro']), 'country_id' => PbCountry::findByCode('MH')->id],
            ['name' => json_encode(['en' => 'Fort-de-France']), 'country_id' => PbCountry::findByCode('MQ')->id],
            ['name' => json_encode(['en' => 'Nuakchot']), 'country_id' => PbCountry::findByCode('MR')->id],
            ['name' => json_encode(['en' => 'Port-Louis']), 'country_id' => PbCountry::findByCode('MU')->id],
            ['name' => json_encode(['en' => 'Ciudad de México']), 'country_id' => PbCountry::findByCode('MX')->id],
            ['name' => json_encode(['en' => 'Chișinău']), 'country_id' => PbCountry::findByCode('MD')->id],
            ['name' => json_encode(['en' => 'Monaco']), 'country_id' => PbCountry::findByCode('MC')->id],
            ['name' => json_encode(['en' => 'Ulaanbaatar']), 'country_id' => PbCountry::findByCode('MN')->id],
            ['name' => json_encode(['en' => 'Podgorica']), 'country_id' => PbCountry::findByCode('ME')->id],
            ['name' => json_encode(['en' => 'Rabat']), 'country_id' => PbCountry::findByCode('MA')->id],
            ['name' => json_encode(['en' => 'Maputo']), 'country_id' => PbCountry::findByCode('MZ')->id],
            ['name' => json_encode(['en' => 'Naypyidaw']), 'country_id' => PbCountry::findByCode('MM')->id],
            ['name' => json_encode(['en' => 'Windhoek']), 'country_id' => PbCountry::findByCode('NA')->id],
            ['name' => json_encode(['en' => 'Yaren']), 'country_id' => PbCountry::findByCode('NR')->id],
            ['name' => json_encode(['en' => 'Kathmandu']), 'country_id' => PbCountry::findByCode('NP')->id],
            ['name' => json_encode(['en' => 'Amsterdam']), 'country_id' => PbCountry::findByCode('NL')->id],
            ['name' => json_encode(['en' => 'Wellington']), 'country_id' => PbCountry::findByCode('NZ')->id],
            ['name' => json_encode(['en' => 'Managua']), 'country_id' => PbCountry::findByCode('NI')->id],
            ['name' => json_encode(['en' => 'Niamey']), 'country_id' => PbCountry::findByCode('NE')->id],
            ['name' => json_encode(['en' => 'Abuya']), 'country_id' => PbCountry::findByCode('NG')->id],
            ['name' => json_encode(['en' => 'Oslo']), 'country_id' => PbCountry::findByCode('NO')->id],
            ['name' => json_encode(['en' => 'Mascate']), 'country_id' => PbCountry::findByCode('OM')->id],
            ['name' => json_encode(['en' => 'Islamabad']), 'country_id' => PbCountry::findByCode('PK')->id],
            ['name' => json_encode(['en' => 'Melekeok']), 'country_id' => PbCountry::findByCode('PW')->id],
            ['name' => json_encode(['en' => 'Panama']), 'country_id' => PbCountry::findByCode('PA')->id],
            ['name' => json_encode(['en' => 'Port Moresby']), 'country_id' => PbCountry::findByCode('PG')->id],
            ['name' => json_encode(['en' => 'Asunción']), 'country_id' => PbCountry::findByCode('PY')->id],
            ['name' => json_encode(['en' => 'Lima']), 'country_id' => PbCountry::findByCode('PE')->id],
            ['name' => json_encode(['en' => 'Manila']), 'country_id' => PbCountry::findByCode('PH')->id],
            ['name' => json_encode(['en' => 'Warsaw']), 'country_id' => PbCountry::findByCode('PL')->id],
            ['name' => json_encode(['en' => 'Lisboa']), 'country_id' => PbCountry::findByCode('PT')->id],
            ['name' => json_encode(['en' => 'San Juan']), 'country_id' => PbCountry::findByCode('PR')->id],
            ['name' => json_encode(['en' => 'Doha']), 'country_id' => PbCountry::findByCode('QA')->id],
            ['name' => json_encode(['en' => 'Brazzaville']), 'country_id' => PbCountry::findByCode('CG')->id],
            ['name' => json_encode(['en' => 'Bucarest']), 'country_id' => PbCountry::findByCode('RO')->id],
            ['name' => json_encode(['en' => 'Moscow']), 'country_id' => PbCountry::findByCode('RU')->id],
            ['name' => json_encode(['en' => 'Kigali']), 'country_id' => PbCountry::findByCode('RW')->id],
            ['name' => json_encode(['en' => 'Kingstown']), 'country_id' => PbCountry::findByCode('VC')->id],
            ['name' => json_encode(['en' => 'Apia']), 'country_id' => PbCountry::findByCode('WS')->id],
            ['name' => json_encode(['en' => 'San Marino']), 'country_id' => PbCountry::findByCode('SM')->id],
            ['name' => json_encode(['en' => 'Sao Tome']), 'country_id' => PbCountry::findByCode('ST')->id],
            ['name' => json_encode(['en' => 'Riad']), 'country_id' => PbCountry::findByCode('SA')->id],
            ['name' => json_encode(['en' => 'Dakar']), 'country_id' => PbCountry::findByCode('SN')->id],
            ['name' => json_encode(['en' => 'Belgrado']), 'country_id' => PbCountry::findByCode('RS')->id],
            ['name' => json_encode(['en' => 'Victoria']), 'country_id' => PbCountry::findByCode('SC')->id],
            ['name' => json_encode(['en' => 'Freetown']), 'country_id' => PbCountry::findByCode('SL')->id],
            ['name' => json_encode(['en' => 'Singapore']), 'country_id' => PbCountry::findByCode('SG')->id],
            ['name' => json_encode(['en' => 'Bratislava']), 'country_id' => PbCountry::findByCode('SK')->id],
            ['name' => json_encode(['en' => 'Liubliana']), 'country_id' => PbCountry::findByCode('SI')->id],
            ['name' => json_encode(['en' => 'Honiara']), 'country_id' => PbCountry::findByCode('SB')->id],
            ['name' => json_encode(['en' => 'Mogadiscio']), 'country_id' => PbCountry::findByCode('SO')->id],
            ['name' => json_encode(['en' => 'Pretoria']), 'country_id' => PbCountry::findByCode('ZA')->id],
            ['name' => json_encode(['en' => 'Seul']), 'country_id' => PbCountry::findByCode('KR')->id],
            ['name' => json_encode(['en' => 'Yuba']), 'country_id' => PbCountry::findByCode('SS')->id],
            ['name' => json_encode(['en' => 'Madrid']), 'country_id' => PbCountry::findByCode('ES')->id],
            ['name' => json_encode(['en' => 'Sri Jayewardenepura']), 'country_id' => PbCountry::findByCode('LK')->id],
            ['name' => json_encode(['en' => 'Castries']), 'country_id' => PbCountry::findByCode('LC')->id],
            ['name' => json_encode(['en' => 'Paramaribo']), 'country_id' => PbCountry::findByCode('SR')->id],
            ['name' => json_encode(['en' => 'Mbabane']), 'country_id' => PbCountry::findByCode('SZ')->id],
            ['name' => json_encode(['en' => 'Stockholm']), 'country_id' => PbCountry::findByCode('SE')->id],
            ['name' => json_encode(['en' => 'Berna']), 'country_id' => PbCountry::findByCode('CH')->id],
            ['name' => json_encode(['en' => 'Taipei']), 'country_id' => PbCountry::findByCode('TW')->id],
            ['name' => json_encode(['en' => 'Dushanbe']), 'country_id' => PbCountry::findByCode('TJ')->id],
            ['name' => json_encode(['en' => 'Dodoma']), 'country_id' => PbCountry::findByCode('TZ')->id],
            ['name' => json_encode(['en' => 'Bangkok']), 'country_id' => PbCountry::findByCode('TH')->id],
            ['name' => json_encode(['en' => 'Nassau']), 'country_id' => PbCountry::findByCode('BS')->id],
            ['name' => json_encode(['en' => 'Banjul']), 'country_id' => PbCountry::findByCode('GM')->id],
            ['name' => json_encode(['en' => 'Dili']), 'country_id' => PbCountry::findByCode('TL')->id],
            ['name' => json_encode(['en' => 'Lomé']), 'country_id' => PbCountry::findByCode('TG')->id],
            ['name' => json_encode(['en' => 'Nukunonu']), 'country_id' => PbCountry::findByCode('TK')->id],
            ['name' => json_encode(['en' => 'Nukualofa']), 'country_id' => PbCountry::findByCode('TO')->id],
            ['name' => json_encode(['en' => 'Puerto España']), 'country_id' => PbCountry::findByCode('TT')->id],
            ['name' => json_encode(['en' => 'Tunisia']), 'country_id' => PbCountry::findByCode('TN')->id],
            ['name' => json_encode(['en' => 'Ankara']), 'country_id' => PbCountry::findByCode('TR')->id],
            ['name' => json_encode(['en' => 'Asjabad']), 'country_id' => PbCountry::findByCode('TM')->id],
            ['name' => json_encode(['en' => 'Fongafale']), 'country_id' => PbCountry::findByCode('TV')->id],
            ['name' => json_encode(['en' => 'Kampala']), 'country_id' => PbCountry::findByCode('UG')->id],
            ['name' => json_encode(['en' => 'Kiev']), 'country_id' => PbCountry::findByCode('UA')->id],
            ['name' => json_encode(['en' => 'Abu Dabi']), 'country_id' => PbCountry::findByCode('AE')->id],
            ['name' => json_encode(['en' => 'London']), 'country_id' => PbCountry::findByCode('GB')->id],
            ['name' => json_encode(['en' => 'Washington, D.C.']), 'country_id' => PbCountry::findByCode('US')->id],
            ['name' => json_encode(['en' => 'Montevideo']), 'country_id' => PbCountry::findByCode('UY')->id],
            ['name' => json_encode(['en' => 'Taskent']), 'country_id' => PbCountry::findByCode('UZ')->id],
            ['name' => json_encode(['en' => 'Port Vila']), 'country_id' => PbCountry::findByCode('VU')->id],
            ['name' => json_encode(['en' => 'Vatican City']), 'country_id' => PbCountry::findByCode('VA')->id],
            ['name' => json_encode(['en' => 'Caracas']), 'country_id' => PbCountry::findByCode('VE')->id],
            ['name' => json_encode(['en' => 'Hanoi']), 'country_id' => PbCountry::findByCode('VN')->id],
            ['name' => json_encode(['en' => 'Sana\'a']), 'country_id' => PbCountry::findByCode('YE')->id],
            ['name' => json_encode(['en' => 'Lusaka']), 'country_id' => PbCountry::findByCode('ZM')->id],
            ['name' => json_encode(['en' => 'Harare']), 'country_id' => PbCountry::findByCode('ZW')->id],
            ['name' => json_encode(['en' => 'Tehrān']), 'country_id' => PbCountry::findByCode('IR')->id],
            ['name' => json_encode(['en' => 'La Habana']), 'country_id' => PbCountry::findByCode('CU')->id],
            ['name' => json_encode(['en' => 'Pionyang']), 'country_id' => PbCountry::findByCode('KP')->id],
            ['name' => json_encode(['en' => 'Damasco']), 'country_id' => PbCountry::findByCode('SY')->id],
            ['name' => json_encode(['en' => 'Khartoum']), 'country_id' => PbCountry::findByCode('SD')->id],
        ], ['name'], ['country_id']);

        $cities = City::all();
        foreach ($cities as $city) {
            $country = PbCountry::find($city->country_id);
            $country->capital_id = $city->id;
            $country->save();
        }
    }
}
