<?php

namespace Anibalealvarezs\Projectbuilder\Database\Seeders;

use Anibalealvarezs\Projectbuilder\Models\PbCity as City;
use Illuminate\Database\Seeder;

class PbCitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (City::count() == 0) {
            // Default Cities
            City::updateOrCreate(['name' => 'Kabul'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Mariehamn'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Tirana'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Argel'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Andorra la Vieja'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Luanda'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Saint John’s'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Buenos Aires'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Ereván'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Camberra'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Viena'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Bakú'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Manama'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Daca'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Bridgetown'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Minsk'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Bruselas'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Belmopán'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Porto Novo & Cotonú'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Timbu'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'La Paz'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Sarajevo'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Gaborone'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Brasilia'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Bandar Seri Begawan'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Sofía'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Uagadugú'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Buyumbura'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Nom Pen'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Yaundé'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Ottawa'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Praia'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Bangui'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Yamena'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Santiago de Chile'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Beijing'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Bogotá'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Moroni'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'San José'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Yamusukro'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Zagreb'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Nicosia'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Praga'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Kinsasa'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Copenhague'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Djibouti'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Roseau'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Santo Domingo'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Quito'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Cairo'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'San Salvador'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Malabo'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Asmara'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Tallin'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Adís Abeba'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Suva'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Helsinki'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Paris'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Libreville'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Tiflis'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Berlin'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Acra'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Atenas'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Saint George'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Ciudad de Guatemala'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Conakri'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Bissau'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Georgetown'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Port-au-Prince'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Tegucigalpa'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Budapest'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Reikiavik'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Nueva Delhi'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Yakarta'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Bagdad'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Dublin'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Jerusalem'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Roma'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Kingston'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Tokyo'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Amman'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Astana'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Nairobi'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Tarawa'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Kuwait'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Biskek'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Vientiane'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Riga'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Beirut'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Maseru'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Monrovia'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Tripoli'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Vaduz'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Vilna'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Luxembourg'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Antananarivo'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Lilongwe'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Kuala Lumpur'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Malé'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Bamako'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Valletta'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Majuro'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Nuakchot'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Port-Louis'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Ciudad de México'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Chișinău'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Monaco'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Ulaanbaatar'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Podgorica'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Rabat'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Maputo'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Windhoek'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Yaren'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Kathmandu'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Amsterdam'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Wellington'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Managua'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Niamey'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Abuya'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Oslo'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Mascate'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Islamabad'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Melekeok'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Panama'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Port Moresby'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Asunción'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Lima'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Manila'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Warsaw'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Lisboa'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'San Juan'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Doha'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Brazzaville'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Bucarest'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Moscow'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Kigali'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Kingstown'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Apia'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'San Marino'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Sao Tome'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Riad'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Dakar'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Belgrado'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Victoria'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Freetown'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Singapore'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Bratislava'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Liubliana'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Honiara'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Mogadiscio'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Pretoria'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Seul'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Yuba'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Madrid'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Sri Jayewardenepura'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Castries'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Paramaribo'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Mbabane'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Stockholm'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Berna'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Dushanbe'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Dodoma'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Bangkok'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Nassau'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Banjul'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Dili'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Lomé'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Nukualofa'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Puerto España'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Tunisia'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Ankara'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Asjabad'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Fongafale'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Kampala'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Kiev'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Abu Dabi'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'London'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Washington, D.C.'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Montevideo'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Taskent'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Port Vila'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Vatican City'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Caracas'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Hanoi'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Sana\'a'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Lusaka'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Harare'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Tehrān'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'La Habana'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Pionyang'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Damasco'], ['country_id' => null]);
            City::updateOrCreate(['name' => 'Khartoum'], ['country_id' => null]);
        }
    }
}
