<?php

namespace Anibalealvarezs\Projectbuilder\Database\Seeders;

use Anibalealvarezs\Projectbuilder\Models\PbCountry as Country;
use Illuminate\Database\Seeder;

class PbCountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Default Countries
        Country::upsert([
            ['code' => 'AF', 'name' => json_encode(['en' => 'Afghanistan'])],
            ['code' => 'AX', 'name' => json_encode(['en' => 'Aland Islands'])],
            ['code' => 'AL', 'name' => json_encode(['en' => 'Albania'])],
            ['code' => 'DZ', 'name' => json_encode(['en' => 'Algeria'])],
            ['code' => 'AS', 'name' => json_encode(['en' => 'American Samoa'])],
            ['code' => 'AD', 'name' => json_encode(['en' => 'Andorra'])],
            ['code' => 'AO', 'name' => json_encode(['en' => 'Angola'])],
            ['code' => 'AI', 'name' => json_encode(['en' => 'Anguilla'])],
            ['code' => 'AQ', 'name' => json_encode(['en' => 'Antarctica'])],
            ['code' => 'AG', 'name' => json_encode(['en' => 'Antigua'])],
            ['code' => 'AR', 'name' => json_encode(['en' => 'Argentina'])],
            ['code' => 'AM', 'name' => json_encode(['en' => 'Armenia'])],
            ['code' => 'AW', 'name' => json_encode(['en' => 'Aruba'])],
            ['code' => 'AU', 'name' => json_encode(['en' => 'Australia'])],
            ['code' => 'AT', 'name' => json_encode(['en' => 'Austria'])],
            ['code' => 'AZ', 'name' => json_encode(['en' => 'Azerbaijan'])],
            ['code' => 'BH', 'name' => json_encode(['en' => 'Bahrain'])],
            ['code' => 'BD', 'name' => json_encode(['en' => 'Bangladesh'])],
            ['code' => 'BB', 'name' => json_encode(['en' => 'Barbados'])],
            ['code' => 'BY', 'name' => json_encode(['en' => 'Belarus'])],
            ['code' => 'BE', 'name' => json_encode(['en' => 'Belgium'])],
            ['code' => 'BZ', 'name' => json_encode(['en' => 'Belize'])],
            ['code' => 'BJ', 'name' => json_encode(['en' => 'Benin'])],
            ['code' => 'BM', 'name' => json_encode(['en' => 'Bermuda'])],
            ['code' => 'BT', 'name' => json_encode(['en' => 'Bhutan'])],
            ['code' => 'BO', 'name' => json_encode(['en' => 'Bolivia'])],
            ['code' => 'BQ', 'name' => json_encode(['en' => 'Bonaire, Sint Eustatius and Saba'])],
            ['code' => 'BA', 'name' => json_encode(['en' => 'Bosnia and Herzegovina'])],
            ['code' => 'BW', 'name' => json_encode(['en' => 'Botswana'])],
            ['code' => 'BV', 'name' => json_encode(['en' => 'Bouvet Island'])],
            ['code' => 'BR', 'name' => json_encode(['en' => 'Brazil'])],
            ['code' => 'IO', 'name' => json_encode(['en' => 'British Indian Ocean Territory'])],
            ['code' => 'VG', 'name' => json_encode(['en' => 'British Virgin Islands'])],
            ['code' => 'BN', 'name' => json_encode(['en' => 'Brunei'])],
            ['code' => 'BG', 'name' => json_encode(['en' => 'Bulgaria'])],
            ['code' => 'BF', 'name' => json_encode(['en' => 'Burkina Faso'])],
            ['code' => 'BI', 'name' => json_encode(['en' => 'Burundi'])],
            ['code' => 'KH', 'name' => json_encode(['en' => 'Cambodia'])],
            ['code' => 'CM', 'name' => json_encode(['en' => 'Cameroon'])],
            ['code' => 'CA', 'name' => json_encode(['en' => 'Canada'])],
            ['code' => 'CV', 'name' => json_encode(['en' => 'Cape Verde'])],
            ['code' => 'KY', 'name' => json_encode(['en' => 'Cayman Islands'])],
            ['code' => 'CF', 'name' => json_encode(['en' => 'Central African Republic'])],
            ['code' => 'TD', 'name' => json_encode(['en' => 'Chad'])],
            ['code' => 'CL', 'name' => json_encode(['en' => 'Chile'])],
            ['code' => 'CN', 'name' => json_encode(['en' => 'China'])],
            ['code' => 'CX', 'name' => json_encode(['en' => 'Christmas Island'])],
            ['code' => 'CC', 'name' => json_encode(['en' => 'Cocos (Keeling) Islands'])],
            ['code' => 'CO', 'name' => json_encode(['en' => 'Colombia'])],
            ['code' => 'KM', 'name' => json_encode(['en' => 'Comoros'])],
            ['code' => 'CK', 'name' => json_encode(['en' => 'Cook Islands'])],
            ['code' => 'CR', 'name' => json_encode(['en' => 'Costa Rica'])],
            ['code' => 'CI', 'name' => json_encode(['en' => 'Côte d\'Ivoire'])],
            ['code' => 'HR', 'name' => json_encode(['en' => 'Croatia'])],
            ['code' => 'CW', 'name' => json_encode(['en' => 'Curaçao'])],
            ['code' => 'CY', 'name' => json_encode(['en' => 'Cyprus'])],
            ['code' => 'CZ', 'name' => json_encode(['en' => 'Czech Republic'])],
            ['code' => 'CD', 'name' => json_encode(['en' => 'Democratic Republic of the Congo'])],
            ['code' => 'DK', 'name' => json_encode(['en' => 'Denmark'])],
            ['code' => 'DJ', 'name' => json_encode(['en' => 'Djibouti'])],
            ['code' => 'DM', 'name' => json_encode(['en' => 'Dominica'])],
            ['code' => 'DO', 'name' => json_encode(['en' => 'Dominican Republic'])],
            ['code' => 'EC', 'name' => json_encode(['en' => 'Ecuador'])],
            ['code' => 'EG', 'name' => json_encode(['en' => 'Egypt'])],
            ['code' => 'SV', 'name' => json_encode(['en' => 'El Salvador'])],
            ['code' => 'GQ', 'name' => json_encode(['en' => 'Equatorial Guinea'])],
            ['code' => 'ER', 'name' => json_encode(['en' => 'Eritrea'])],
            ['code' => 'EE', 'name' => json_encode(['en' => 'Estonia'])],
            ['code' => 'ET', 'name' => json_encode(['en' => 'Ethiopia'])],
            ['code' => 'FK', 'name' => json_encode(['en' => 'Falkland Islands'])],
            ['code' => 'FO', 'name' => json_encode(['en' => 'Faroe Islands'])],
            ['code' => 'FM', 'name' => json_encode(['en' => 'Federated States of Micronesia'])],
            ['code' => 'FJ', 'name' => json_encode(['en' => 'Fiji'])],
            ['code' => 'FI', 'name' => json_encode(['en' => 'Finland'])],
            ['code' => 'FR', 'name' => json_encode(['en' => 'France'])],
            ['code' => 'GF', 'name' => json_encode(['en' => 'French Guiana'])],
            ['code' => 'PF', 'name' => json_encode(['en' => 'French Polynesia'])],
            ['code' => 'TF', 'name' => json_encode(['en' => 'French Southern Territories'])],
            ['code' => 'GA', 'name' => json_encode(['en' => 'Gabon'])],
            ['code' => 'GE', 'name' => json_encode(['en' => 'Georgia'])],
            ['code' => 'DE', 'name' => json_encode(['en' => 'Germany'])],
            ['code' => 'GH', 'name' => json_encode(['en' => 'Ghana'])],
            ['code' => 'GI', 'name' => json_encode(['en' => 'Gibraltar'])],
            ['code' => 'GR', 'name' => json_encode(['en' => 'Greece'])],
            ['code' => 'GL', 'name' => json_encode(['en' => 'Greenland'])],
            ['code' => 'GD', 'name' => json_encode(['en' => 'Grenada'])],
            ['code' => 'GP', 'name' => json_encode(['en' => 'Guadeloupe'])],
            ['code' => 'GU', 'name' => json_encode(['en' => 'Guam'])],
            ['code' => 'GT', 'name' => json_encode(['en' => 'Guatemala'])],
            ['code' => 'GG', 'name' => json_encode(['en' => 'Guernsey'])],
            ['code' => 'GN', 'name' => json_encode(['en' => 'Guinea'])],
            ['code' => 'GW', 'name' => json_encode(['en' => 'Guinea-Bissau'])],
            ['code' => 'GY', 'name' => json_encode(['en' => 'Guyana'])],
            ['code' => 'HT', 'name' => json_encode(['en' => 'Haiti'])],
            ['code' => 'HM', 'name' => json_encode(['en' => 'Heard Island and McDonald Islands'])],
            ['code' => 'HN', 'name' => json_encode(['en' => 'Honduras'])],
            ['code' => 'HK', 'name' => json_encode(['en' => 'Hong Kong'])],
            ['code' => 'HU', 'name' => json_encode(['en' => 'Hungary'])],
            ['code' => 'IS', 'name' => json_encode(['en' => 'Iceland'])],
            ['code' => 'IN', 'name' => json_encode(['en' => 'India'])],
            ['code' => 'ID', 'name' => json_encode(['en' => 'Indonesia'])],
            ['code' => 'IQ', 'name' => json_encode(['en' => 'Iraq'])],
            ['code' => 'IE', 'name' => json_encode(['en' => 'Ireland'])],
            ['code' => 'IM', 'name' => json_encode(['en' => 'Isle Of Man'])],
            ['code' => 'IL', 'name' => json_encode(['en' => 'Israel'])],
            ['code' => 'IT', 'name' => json_encode(['en' => 'Italy'])],
            ['code' => 'JM', 'name' => json_encode(['en' => 'Jamaica'])],
            ['code' => 'JP', 'name' => json_encode(['en' => 'Japan'])],
            ['code' => 'JE', 'name' => json_encode(['en' => 'Jersey'])],
            ['code' => 'JO', 'name' => json_encode(['en' => 'Jordan'])],
            ['code' => 'KZ', 'name' => json_encode(['en' => 'Kazakhstan'])],
            ['code' => 'KE', 'name' => json_encode(['en' => 'Kenya'])],
            ['code' => 'KI', 'name' => json_encode(['en' => 'Kiribati'])],
            ['code' => 'XK', 'name' => json_encode(['en' => 'Kosovo'])],
            ['code' => 'KW', 'name' => json_encode(['en' => 'Kuwait'])],
            ['code' => 'KG', 'name' => json_encode(['en' => 'Kyrgyzstan'])],
            ['code' => 'LA', 'name' => json_encode(['en' => 'Laos'])],
            ['code' => 'LV', 'name' => json_encode(['en' => 'Latvia'])],
            ['code' => 'LB', 'name' => json_encode(['en' => 'Lebanon'])],
            ['code' => 'LS', 'name' => json_encode(['en' => 'Lesotho'])],
            ['code' => 'LR', 'name' => json_encode(['en' => 'Liberia'])],
            ['code' => 'LY', 'name' => json_encode(['en' => 'Libya'])],
            ['code' => 'LI', 'name' => json_encode(['en' => 'Liechtenstein'])],
            ['code' => 'LT', 'name' => json_encode(['en' => 'Lithuania'])],
            ['code' => 'LU', 'name' => json_encode(['en' => 'Luxembourg'])],
            ['code' => 'MO', 'name' => json_encode(['en' => 'Macau'])],
            ['code' => 'MK', 'name' => json_encode(['en' => 'Macedonia'])],
            ['code' => 'MG', 'name' => json_encode(['en' => 'Madagascar'])],
            ['code' => 'MW', 'name' => json_encode(['en' => 'Malawi'])],
            ['code' => 'MY', 'name' => json_encode(['en' => 'Malaysia'])],
            ['code' => 'MV', 'name' => json_encode(['en' => 'Maldives'])],
            ['code' => 'ML', 'name' => json_encode(['en' => 'Mali'])],
            ['code' => 'MT', 'name' => json_encode(['en' => 'Malta'])],
            ['code' => 'MH', 'name' => json_encode(['en' => 'Marshall Islands'])],
            ['code' => 'MQ', 'name' => json_encode(['en' => 'Martinique'])],
            ['code' => 'MR', 'name' => json_encode(['en' => 'Mauritania'])],
            ['code' => 'MU', 'name' => json_encode(['en' => 'Mauritius'])],
            ['code' => 'YT', 'name' => json_encode(['en' => 'Mayotte'])],
            ['code' => 'MX', 'name' => json_encode(['en' => 'Mexico'])],
            ['code' => 'MD', 'name' => json_encode(['en' => 'Moldova'])],
            ['code' => 'MC', 'name' => json_encode(['en' => 'Monaco'])],
            ['code' => 'MN', 'name' => json_encode(['en' => 'Mongolia'])],
            ['code' => 'ME', 'name' => json_encode(['en' => 'Montenegro'])],
            ['code' => 'MS', 'name' => json_encode(['en' => 'Montserrat'])],
            ['code' => 'MA', 'name' => json_encode(['en' => 'Morocco'])],
            ['code' => 'MZ', 'name' => json_encode(['en' => 'Mozambique'])],
            ['code' => 'MM', 'name' => json_encode(['en' => 'Myanmar'])],
            ['code' => 'NA', 'name' => json_encode(['en' => 'Namibia'])],
            ['code' => 'NR', 'name' => json_encode(['en' => 'Nauru'])],
            ['code' => 'NP', 'name' => json_encode(['en' => 'Nepal'])],
            ['code' => 'NL', 'name' => json_encode(['en' => 'Netherlands'])],
            ['code' => 'AN', 'name' => json_encode(['en' => 'Netherlands Antilles'])],
            ['code' => 'NC', 'name' => json_encode(['en' => 'New Caledonia'])],
            ['code' => 'NZ', 'name' => json_encode(['en' => 'New Zealand'])],
            ['code' => 'NI', 'name' => json_encode(['en' => 'Nicaragua'])],
            ['code' => 'NE', 'name' => json_encode(['en' => 'Niger'])],
            ['code' => 'NG', 'name' => json_encode(['en' => 'Nigeria'])],
            ['code' => 'NU', 'name' => json_encode(['en' => 'Niue'])],
            ['code' => 'NF', 'name' => json_encode(['en' => 'Norfolk Island'])],
            ['code' => 'MP', 'name' => json_encode(['en' => 'Northern Mariana Islands'])],
            ['code' => 'NO', 'name' => json_encode(['en' => 'Norway'])],
            ['code' => 'OM', 'name' => json_encode(['en' => 'Oman'])],
            ['code' => 'PK', 'name' => json_encode(['en' => 'Pakistan'])],
            ['code' => 'PW', 'name' => json_encode(['en' => 'Palau'])],
            ['code' => 'PS', 'name' => json_encode(['en' => 'Palestine'])],
            ['code' => 'PA', 'name' => json_encode(['en' => 'Panama'])],
            ['code' => 'PG', 'name' => json_encode(['en' => 'Papua New Guinea'])],
            ['code' => 'PY', 'name' => json_encode(['en' => 'Paraguay'])],
            ['code' => 'PE', 'name' => json_encode(['en' => 'Peru'])],
            ['code' => 'PH', 'name' => json_encode(['en' => 'Philippines'])],
            ['code' => 'PN', 'name' => json_encode(['en' => 'Pitcairn'])],
            ['code' => 'PL', 'name' => json_encode(['en' => 'Poland'])],
            ['code' => 'PT', 'name' => json_encode(['en' => 'Portugal'])],
            ['code' => 'PR', 'name' => json_encode(['en' => 'Puerto Rico'])],
            ['code' => 'QA', 'name' => json_encode(['en' => 'Qatar'])],
            ['code' => 'CG', 'name' => json_encode(['en' => 'Republic of the Congo'])],
            ['code' => 'RO', 'name' => json_encode(['en' => 'Romania'])],
            ['code' => 'RU', 'name' => json_encode(['en' => 'Russia'])],
            ['code' => 'RW', 'name' => json_encode(['en' => 'Rwanda'])],
            ['code' => 'RE', 'name' => json_encode(['en' => 'Réunion'])],
            ['code' => 'BL', 'name' => json_encode(['en' => 'Saint Barthélemy'])],
            ['code' => 'SH', 'name' => json_encode(['en' => 'Saint Helena'])],
            ['code' => 'KN', 'name' => json_encode(['en' => 'Saint Kitts and Nevis'])],
            ['code' => 'MF', 'name' => json_encode(['en' => 'Saint Martin'])],
            ['code' => 'PM', 'name' => json_encode(['en' => 'Saint Pierre and Miquelon'])],
            ['code' => 'VC', 'name' => json_encode(['en' => 'Saint Vincent and the Grenadines'])],
            ['code' => 'WS', 'name' => json_encode(['en' => 'Samoa'])],
            ['code' => 'SM', 'name' => json_encode(['en' => 'San Marino'])],
            ['code' => 'ST', 'name' => json_encode(['en' => 'Sao Tome and Principe'])],
            ['code' => 'SA', 'name' => json_encode(['en' => 'Saudi Arabia'])],
            ['code' => 'SN', 'name' => json_encode(['en' => 'Senegal'])],
            ['code' => 'RS', 'name' => json_encode(['en' => 'Serbia'])],
            ['code' => 'SC', 'name' => json_encode(['en' => 'Seychelles'])],
            ['code' => 'SL', 'name' => json_encode(['en' => 'Sierra Leone'])],
            ['code' => 'SG', 'name' => json_encode(['en' => 'Singapore'])],
            ['code' => 'SX', 'name' => json_encode(['en' => 'Sint Maarten'])],
            ['code' => 'SK', 'name' => json_encode(['en' => 'Slovakia'])],
            ['code' => 'SI', 'name' => json_encode(['en' => 'Slovenia'])],
            ['code' => 'SB', 'name' => json_encode(['en' => 'Solomon Islands'])],
            ['code' => 'SO', 'name' => json_encode(['en' => 'Somalia'])],
            ['code' => 'ZA', 'name' => json_encode(['en' => 'South Africa'])],
            ['code' => 'GS', 'name' => json_encode(['en' => 'South Georgia and the South Sandwich Islands'])],
            ['code' => 'KR', 'name' => json_encode(['en' => 'South Korea'])],
            ['code' => 'SS', 'name' => json_encode(['en' => 'South Sudan'])],
            ['code' => 'ES', 'name' => json_encode(['en' => 'Spain'])],
            ['code' => 'LK', 'name' => json_encode(['en' => 'Sri Lanka'])],
            ['code' => 'LC', 'name' => json_encode(['en' => 'St. Lucia'])],
            ['code' => 'SR', 'name' => json_encode(['en' => 'Suriname'])],
            ['code' => 'SJ', 'name' => json_encode(['en' => 'Svalbard and Jan Mayen'])],
            ['code' => 'SZ', 'name' => json_encode(['en' => 'Swaziland'])],
            ['code' => 'SE', 'name' => json_encode(['en' => 'Sweden'])],
            ['code' => 'CH', 'name' => json_encode(['en' => 'Switzerland'])],
            ['code' => 'TW', 'name' => json_encode(['en' => 'Taiwan'])],
            ['code' => 'TJ', 'name' => json_encode(['en' => 'Tajikistan'])],
            ['code' => 'TZ', 'name' => json_encode(['en' => 'Tanzania'])],
            ['code' => 'TH', 'name' => json_encode(['en' => 'Thailand'])],
            ['code' => 'BS', 'name' => json_encode(['en' => 'The Bahamas'])],
            ['code' => 'GM', 'name' => json_encode(['en' => 'The Gambia'])],
            ['code' => 'TL', 'name' => json_encode(['en' => 'Timor-Leste'])],
            ['code' => 'TG', 'name' => json_encode(['en' => 'Togo'])],
            ['code' => 'TK', 'name' => json_encode(['en' => 'Tokelau'])],
            ['code' => 'TO', 'name' => json_encode(['en' => 'Tonga'])],
            ['code' => 'TT', 'name' => json_encode(['en' => 'Trinidad and Tobago'])],
            ['code' => 'TN', 'name' => json_encode(['en' => 'Tunisia'])],
            ['code' => 'TR', 'name' => json_encode(['en' => 'Turkey'])],
            ['code' => 'TM', 'name' => json_encode(['en' => 'Turkmenistan'])],
            ['code' => 'TC', 'name' => json_encode(['en' => 'Turks and Caicos Islands'])],
            ['code' => 'TV', 'name' => json_encode(['en' => 'Tuvalu'])],
            ['code' => 'VI', 'name' => json_encode(['en' => 'US Virgin Islands'])],
            ['code' => 'UG', 'name' => json_encode(['en' => 'Uganda'])],
            ['code' => 'UA', 'name' => json_encode(['en' => 'Ukraine'])],
            ['code' => 'AE', 'name' => json_encode(['en' => 'United Arab Emirates'])],
            ['code' => 'GB', 'name' => json_encode(['en' => 'United Kingdom'])],
            ['code' => 'US', 'name' => json_encode(['en' => 'United States'])],
            ['code' => 'UM', 'name' => json_encode(['en' => 'United States Minor Outlying Islands'])],
            ['code' => 'UY', 'name' => json_encode(['en' => 'Uruguay'])],
            ['code' => 'UZ', 'name' => json_encode(['en' => 'Uzbekistan'])],
            ['code' => 'VU', 'name' => json_encode(['en' => 'Vanuatu'])],
            ['code' => 'VA', 'name' => json_encode(['en' => 'Vatican City'])],
            ['code' => 'VE', 'name' => json_encode(['en' => 'Venezuela'])],
            ['code' => 'VN', 'name' => json_encode(['en' => 'Vietnam'])],
            ['code' => 'WF', 'name' => json_encode(['en' => 'Wallis and Futuna'])],
            ['code' => 'EH', 'name' => json_encode(['en' => 'Western Sahara'])],
            ['code' => 'YE', 'name' => json_encode(['en' => 'Yemen'])],
            ['code' => 'ZM', 'name' => json_encode(['en' => 'Zambia'])],
            ['code' => 'ZW', 'name' => json_encode(['en' => 'Zimbabwe'])],
            ['code' => 'IR', 'name' => json_encode(['en' => 'Iran'])],
            ['code' => 'CU', 'name' => json_encode(['en' => 'Cuba'])],
            ['code' => 'KP', 'name' => json_encode(['en' => 'North Korea'])],
            ['code' => 'SY', 'name' => json_encode(['en' => 'Syria'])],
            ['code' => 'SD', 'name' => json_encode(['en' => 'Sudan'])]
        ], ['code'], ['name']);
    }
}
