<?php

namespace Anibalealvarezs\Projectbuilder\Database\Seeders;

use Anibalealvarezs\Projectbuilder\Models\PbLanguage as Language;
use Illuminate\Database\Seeder;

class PbLanguagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (Language::count() == 0) {
            // Default Languages
            Language::upsert([
                ['code' => 'ab', 'name' => json_encode(['en' => 'Abkhazian', 'es' => 'Abjasio']), 'status' => false],
                ['code' => 'aa', 'name' => json_encode(['en' => 'Afar', 'es' => 'Afar']), 'status' => false],
                ['code' => 'af', 'name' => json_encode(['en' => 'Afrikaans', 'es' => 'Africaans']), 'status' => false],
                ['code' => 'ak', 'name' => json_encode(['en' => 'Akan', 'es' => 'Akan']), 'status' => false],
                ['code' => 'sq', 'name' => json_encode(['en' => 'Albanian', 'es' => 'Albano']), 'status' => false],
                ['code' => 'am', 'name' => json_encode(['en' => 'Amharic', 'es' => 'Amárico']), 'status' => false],
                ['code' => 'ar', 'name' => json_encode(['en' => 'Arabic', 'es' => 'Árabe']), 'status' => false],
                ['code' => 'an', 'name' => json_encode(['en' => 'Aragonese', 'es' => 'Aragonés']), 'status' => false],
                ['code' => 'hy', 'name' => json_encode(['en' => 'Armenian', 'es' => 'Armenio']), 'status' => false],
                ['code' => 'as', 'name' => json_encode(['en' => 'Assamese', 'es' => 'Asamés']), 'status' => false],
                ['code' => 'av', 'name' => json_encode(['en' => 'Avaric', 'es' => 'Avaro']), 'status' => false],
                ['code' => 'ae', 'name' => json_encode(['en' => 'Avestan', 'es' => 'Avéstico']), 'status' => false],
                ['code' => 'ay', 'name' => json_encode(['en' => 'Aymara', 'es' => 'Aymara']), 'status' => false],
                ['code' => 'az', 'name' => json_encode(['en' => 'Azerbaijani', 'es' => 'Azerbaiyano']), 'status' => false],
                ['code' => 'bm', 'name' => json_encode(['en' => 'Bambara', 'es' => 'Bambara']), 'status' => false],
                ['code' => 'ba', 'name' => json_encode(['en' => 'Bashkir', 'es' => 'Bashkir']), 'status' => false],
                ['code' => 'eu', 'name' => json_encode(['en' => 'Basque', 'es' => 'Vasco']), 'status' => false],
                ['code' => 'be', 'name' => json_encode(['en' => 'Belarusian', 'es' => 'Bielorruso']), 'status' => false],
                ['code' => 'bn', 'name' => json_encode(['en' => 'Bengali', 'es' => 'Bengalí']), 'status' => false],
                ['code' => 'bh', 'name' => json_encode(['en' => 'Bihari languages', 'es' => 'Idiomas bihari']), 'status' => false],
                ['code' => 'bi', 'name' => json_encode(['en' => 'Bislama', 'es' => 'Bislama']), 'status' => false],
                ['code' => 'bs', 'name' => json_encode(['en' => 'Bosnian', 'es' => 'Bosnio']), 'status' => false],
                ['code' => 'br', 'name' => json_encode(['en' => 'Breton', 'es' => 'Bretón']), 'status' => false],
                ['code' => 'bg', 'name' => json_encode(['en' => 'Bulgarian', 'es' => 'Búlgaro']), 'status' => false],
                ['code' => 'my', 'name' => json_encode(['en' => 'Burmese', 'es' => 'Birmano']), 'status' => false],
                ['code' => 'ca', 'name' => json_encode(['en' => 'Catalan, Valencian', 'es' => 'Catalán, Valenciano']), 'status' => false],
                ['code' => 'ch', 'name' => json_encode(['en' => 'Chamorro', 'es' => 'Chamorro']), 'status' => false],
                ['code' => 'ce', 'name' => json_encode(['en' => 'Chechen', 'es' => 'Checheno']), 'status' => false],
                ['code' => 'ny', 'name' => json_encode(['en' => 'Chichewa, Chewa, Nyanja', 'es' => 'Chichewa, Chewa, Nyanja']), 'status' => false],
                ['code' => 'zh', 'name' => json_encode(['en' => 'Chinese', 'es' => 'Chino']), 'status' => false],
                ['code' => 'cv', 'name' => json_encode(['en' => 'Chuvash', 'es' => 'Chuvasio']), 'status' => false],
                ['code' => 'kw', 'name' => json_encode(['en' => 'Cornish', 'es' => 'Cornualles']), 'status' => false],
                ['code' => 'co', 'name' => json_encode(['en' => 'Corsican', 'es' => 'Corso']), 'status' => false],
                ['code' => 'cr', 'name' => json_encode(['en' => 'Cree', 'es' => 'Cree']), 'status' => false],
                ['code' => 'hr', 'name' => json_encode(['en' => 'Croatian', 'es' => 'Croata']), 'status' => false],
                ['code' => 'cs', 'name' => json_encode(['en' => 'Czech', 'es' => 'Checo']), 'status' => false],
                ['code' => 'da', 'name' => json_encode(['en' => 'Danish', 'es' => 'Danés']), 'status' => false],
                ['code' => 'dv', 'name' => json_encode(['en' => 'Divehi, Dhivehi, Maldivian', 'es' => 'Divehi, Dhivehi, Maldivas']), 'status' => false],
                ['code' => 'nl', 'name' => json_encode(['en' => 'Dutch, Flemish', 'es' => 'Holandés, Flamenco']), 'status' => false],
                ['code' => 'dz', 'name' => json_encode(['en' => 'Dzongkha', 'es' => 'Dzongkha']), 'status' => false],
                ['code' => 'en', 'name' => json_encode(['en' => 'English', 'es' => 'Inglés']), 'status' => true],
                ['code' => 'eo', 'name' => json_encode(['en' => 'Esperanto', 'es' => 'Esperanto']), 'status' => false],
                ['code' => 'et', 'name' => json_encode(['en' => 'Estonian', 'es' => 'Estonio']), 'status' => false],
                ['code' => 'ee', 'name' => json_encode(['en' => 'Ewe', 'es' => 'Oveja']), 'status' => false],
                ['code' => 'fo', 'name' => json_encode(['en' => 'Faroese', 'es' => 'Feroés']), 'status' => false],
                ['code' => 'fj', 'name' => json_encode(['en' => 'Fijian', 'es' => 'Fiyiano']), 'status' => false],
                ['code' => 'fi', 'name' => json_encode(['en' => 'Finnish', 'es' => 'Finlandés']), 'status' => false],
                ['code' => 'fr', 'name' => json_encode(['en' => 'French', 'es' => 'Francés']), 'status' => false],
                ['code' => 'ff', 'name' => json_encode(['en' => 'Fulah', 'es' => 'Fula']), 'status' => false],
                ['code' => 'gl', 'name' => json_encode(['en' => 'Galician', 'es' => 'Gallego']), 'status' => false],
                ['code' => 'ka', 'name' => json_encode(['en' => 'Georgian', 'es' => 'Georgiano']), 'status' => false],
                ['code' => 'de', 'name' => json_encode(['en' => 'German', 'es' => 'Alemán']), 'status' => false],
                ['code' => 'el', 'name' => json_encode(['en' => 'Greek (modern)', 'es' => 'Griego (moderno)']), 'status' => false],
                ['code' => 'gn', 'name' => json_encode(['en' => 'Guaraní', 'es' => 'Guaraní']), 'status' => false],
                ['code' => 'gu', 'name' => json_encode(['en' => 'Gujarati', 'es' => 'Guyaratí']), 'status' => false],
                ['code' => 'ht', 'name' => json_encode(['en' => 'Haitian, Haitian Creole', 'es' => 'Haitiano, Haitiano Criollo']), 'status' => false],
                ['code' => 'ha', 'name' => json_encode(['en' => 'Hausa', 'es' => 'Hausa']), 'status' => false],
                ['code' => 'he', 'name' => json_encode(['en' => 'Hebrew (modern)', 'es' => 'Hebreo (moderno)']), 'status' => false],
                ['code' => 'hz', 'name' => json_encode(['en' => 'Herero', 'es' => 'Herero']), 'status' => false],
                ['code' => 'hi', 'name' => json_encode(['en' => 'Hindi', 'es' => 'Hindú']), 'status' => false],
                ['code' => 'ho', 'name' => json_encode(['en' => 'Hiri Motu', 'es' => 'Hiri Motu']), 'status' => false],
                ['code' => 'hu', 'name' => json_encode(['en' => 'Hungarian', 'es' => 'Húngaro']), 'status' => false],
                ['code' => 'ia', 'name' => json_encode(['en' => 'Interlingua', 'es' => 'Interlingual']), 'status' => false],
                ['code' => 'id', 'name' => json_encode(['en' => 'Indonesian', 'es' => 'Indonesio']), 'status' => false],
                ['code' => 'ie', 'name' => json_encode(['en' => 'Interlingue', 'es' => 'Interlingüismo']), 'status' => false],
                ['code' => 'ga', 'name' => json_encode(['en' => 'Irish', 'es' => 'Irlandés']), 'status' => false],
                ['code' => 'ig', 'name' => json_encode(['en' => 'Igbo', 'es' => 'Igbo']), 'status' => false],
                ['code' => 'ik', 'name' => json_encode(['en' => 'Inupiaq', 'es' => 'Inupiaq']), 'status' => false],
                ['code' => 'io', 'name' => json_encode(['en' => 'Ido', 'es' => 'Ido']), 'status' => false],
                ['code' => 'is', 'name' => json_encode(['en' => 'Icelandic', 'es' => 'Islandés']), 'status' => false],
                ['code' => 'it', 'name' => json_encode(['en' => 'Italian', 'es' => 'Italiano']), 'status' => false],
                ['code' => 'iu', 'name' => json_encode(['en' => 'Inuktitut', 'es' => 'Inuktitut']), 'status' => false],
                ['code' => 'ja', 'name' => json_encode(['en' => 'Japanese', 'es' => 'Japonés']), 'status' => false],
                ['code' => 'jv', 'name' => json_encode(['en' => 'Javanese', 'es' => 'Javanés']), 'status' => false],
                ['code' => 'kl', 'name' => json_encode(['en' => 'Kalaallisut, Greenlandic', 'es' => 'Kalaallisut, Groenlandés']), 'status' => false],
                ['code' => 'kn', 'name' => json_encode(['en' => 'Kannada', 'es' => 'Canarés']), 'status' => false],
                ['code' => 'kr', 'name' => json_encode(['en' => 'Kanuri', 'es' => 'Kanuri']), 'status' => false],
                ['code' => 'ks', 'name' => json_encode(['en' => 'Kashmiri', 'es' => 'Cachemira']), 'status' => false],
                ['code' => 'kk', 'name' => json_encode(['en' => 'Kazakh', 'es' => 'Kazajo']), 'status' => false],
                ['code' => 'km', 'name' => json_encode(['en' => 'Central Khmer', 'es' => 'Jemer Central']), 'status' => false],
                ['code' => 'ki', 'name' => json_encode(['en' => 'Kikuyu, Gikuyu', 'es' => 'Kikuyú, Gikuyú']), 'status' => false],
                ['code' => 'rw', 'name' => json_encode(['en' => 'Kinyarwanda', 'es' => 'Kinyarwanda']), 'status' => false],
                ['code' => 'ky', 'name' => json_encode(['en' => 'Kirghiz, Kyrgyz', 'es' => 'Kirguís, Kirguistán']), 'status' => false],
                ['code' => 'kv', 'name' => json_encode(['en' => 'Komi', 'es' => 'Komi']), 'status' => false],
                ['code' => 'kg', 'name' => json_encode(['en' => 'Kongo', 'es' => 'Kongo']), 'status' => false],
                ['code' => 'ko', 'name' => json_encode(['en' => 'Korean', 'es' => 'Coreano']), 'status' => false],
                ['code' => 'ku', 'name' => json_encode(['en' => 'Kurdish', 'es' => 'Kurdo']), 'status' => false],
                ['code' => 'kj', 'name' => json_encode(['en' => 'Kuanyama, Kwanyama', 'es' => 'Kuanyama, Kwanyama']), 'status' => false],
                ['code' => 'la', 'name' => json_encode(['en' => 'Latin', 'es' => 'Latín']), 'status' => false],
                ['code' => 'lb', 'name' => json_encode(['en' => 'Luxembourgish, Letzeburgesch', 'es' => 'Luxemburgués, Letzeburgesch']), 'status' => false],
                ['code' => 'lg', 'name' => json_encode(['en' => 'Ganda', 'es' => 'Ganda']), 'status' => false],
                ['code' => 'li', 'name' => json_encode(['en' => 'Limburgan, Limburger, Limburgish', 'es' => 'Limburgués']), 'status' => false],
                ['code' => 'ln', 'name' => json_encode(['en' => 'Lingala', 'es' => 'Lingala']), 'status' => false],
                ['code' => 'lo', 'name' => json_encode(['en' => 'Lao', 'es' => 'Laosiano']), 'status' => false],
                ['code' => 'lt', 'name' => json_encode(['en' => 'Lithuanian', 'es' => 'Lituano']), 'status' => false],
                ['code' => 'lu', 'name' => json_encode(['en' => 'Luba-Katanga', 'es' => 'Luba-Katanga']), 'status' => false],
                ['code' => 'lv', 'name' => json_encode(['en' => 'Latvian', 'es' => 'Letón']), 'status' => false],
                ['code' => 'gv', 'name' => json_encode(['en' => 'Manx', 'es' => 'De la Isla de Man']), 'status' => false],
                ['code' => 'mk', 'name' => json_encode(['en' => 'Macedonian', 'es' => 'Macedonio']), 'status' => false],
                ['code' => 'mg', 'name' => json_encode(['en' => 'Malagasy', 'es' => 'Malagués']), 'status' => false],
                ['code' => 'ms', 'name' => json_encode(['en' => 'Malay', 'es' => 'Malayo']), 'status' => false],
                ['code' => 'ml', 'name' => json_encode(['en' => 'Malayalam', 'es' => 'Malayalam']), 'status' => false],
                ['code' => 'mt', 'name' => json_encode(['en' => 'Maltese', 'es' => 'Maltés']), 'status' => false],
                ['code' => 'mi', 'name' => json_encode(['en' => 'Maori', 'es' => 'Maorí']), 'status' => false],
                ['code' => 'mr', 'name' => json_encode(['en' => 'Marathi', 'es' => 'Marathi']), 'status' => false],
                ['code' => 'mh', 'name' => json_encode(['en' => 'Marshallese', 'es' => 'Marshalés']), 'status' => false],
                ['code' => 'mn', 'name' => json_encode(['en' => 'Mongolian', 'es' => 'Mongol']), 'status' => false],
                ['code' => 'na', 'name' => json_encode(['en' => 'Nauru', 'es' => 'Nauru']), 'status' => false],
                ['code' => 'nv', 'name' => json_encode(['en' => 'Navajo, Navaho', 'es' => 'Navajo']), 'status' => false],
                ['code' => 'nd', 'name' => json_encode(['en' => 'North Ndebele', 'es' => 'Ndebele del norte']), 'status' => false],
                ['code' => 'ne', 'name' => json_encode(['en' => 'Nepali', 'es' => 'Nepalí']), 'status' => false],
                ['code' => 'ng', 'name' => json_encode(['en' => 'Ndonga', 'es' => 'Ndonga']), 'status' => false],
                ['code' => 'nb', 'name' => json_encode(['en' => 'Norwegian Bokmål', 'es' => 'Bokmal noruego']), 'status' => false],
                ['code' => 'nn', 'name' => json_encode(['en' => 'Norwegian Nynorsk', 'es' => 'Nynorsk noruego']), 'status' => false],
                ['code' => 'no', 'name' => json_encode(['en' => 'Norwegian', 'es' => 'Noruego']), 'status' => false],
                ['code' => 'ii', 'name' => json_encode(['en' => 'Sichuan Yi, Nuosu', 'es' => 'Sichuan Yi, Nuosu']), 'status' => false],
                ['code' => 'nr', 'name' => json_encode(['en' => 'South Ndebele', 'es' => 'Ndebele del sur']), 'status' => false],
                ['code' => 'oc', 'name' => json_encode(['en' => 'Occitan', 'es' => 'Occitano']), 'status' => false],
                ['code' => 'oj', 'name' => json_encode(['en' => 'Ojibwa', 'es' => 'Ojibwa']), 'status' => false],
                ['code' => 'cu', 'name' => json_encode(['en' => 'Church Slavic, Church Slavonic, Old Church Slavonic, Old Slavonic, Old Bulgarian', 'es' => '']), 'status' => false],
                ['code' => 'om', 'name' => json_encode(['en' => 'Oromo', 'es' => 'Oromo']), 'status' => false],
                ['code' => 'or', 'name' => json_encode(['en' => 'Oriya', 'es' => 'Oriya']), 'status' => false],
                ['code' => 'os', 'name' => json_encode(['en' => 'Ossetian, Ossetic', 'es' => 'Osetio, osético']), 'status' => false],
                ['code' => 'pa', 'name' => json_encode(['en' => 'Panjabi, Punjabi', 'es' => 'Panyabí, Punjabí']), 'status' => false],
                ['code' => 'pi', 'name' => json_encode(['en' => 'Pali', 'es' => 'Pali']), 'status' => false],
                ['code' => 'fa', 'name' => json_encode(['en' => 'Persian', 'es' => 'Persa']), 'status' => false],
                ['code' => 'po', 'name' => json_encode(['en' => 'Polabian', 'es' => 'Polaco']), 'status' => false],
                ['code' => 'pl', 'name' => json_encode(['en' => 'Polish', 'es' => 'Polaco']), 'status' => false],
                ['code' => 'ps', 'name' => json_encode(['en' => 'Pashto, Pushto', 'es' => 'Pastún']), 'status' => false],
                ['code' => 'pt', 'name' => json_encode(['en' => 'Portuguese', 'es' => 'Portugués']), 'status' => false],
                ['code' => 'qu', 'name' => json_encode(['en' => 'Quechua', 'es' => 'Quechua']), 'status' => false],
                ['code' => 'rm', 'name' => json_encode(['en' => 'Romansh', 'es' => 'Romanche']), 'status' => false],
                ['code' => 'rn', 'name' => json_encode(['en' => 'Rundi', 'es' => 'Rundi']), 'status' => false],
                ['code' => 'ro', 'name' => json_encode(['en' => 'Romanian, Moldavian, Moldovan', 'es' => 'Rumano, Moldavo']), 'status' => false],
                ['code' => 'ru', 'name' => json_encode(['en' => 'Russian', 'es' => 'Ruso']), 'status' => false],
                ['code' => 'sa', 'name' => json_encode(['en' => 'Sanskrit', 'es' => 'Sánscrito']), 'status' => false],
                ['code' => 'sc', 'name' => json_encode(['en' => 'Sardinian', 'es' => 'Sardo']), 'status' => false],
                ['code' => 'sd', 'name' => json_encode(['en' => 'Sindhi', 'es' => 'Sindhi']), 'status' => false],
                ['code' => 'se', 'name' => json_encode(['en' => 'Northern Sami', 'es' => 'Sami del norte']), 'status' => false],
                ['code' => 'sm', 'name' => json_encode(['en' => 'Samoan', 'es' => 'Samoano']), 'status' => false],
                ['code' => 'sg', 'name' => json_encode(['en' => 'Sango', 'es' => 'Sango']), 'status' => false],
                ['code' => 'sr', 'name' => json_encode(['en' => 'Serbian', 'es' => 'Serbio']), 'status' => false],
                ['code' => 'gd', 'name' => json_encode(['en' => 'Gaelic, Scottish Gaelic', 'es' => 'Gaélico, gaélico escocés']), 'status' => false],
                ['code' => 'sn', 'name' => json_encode(['en' => 'Shona', 'es' => 'Shona']), 'status' => false],
                ['code' => 'si', 'name' => json_encode(['en' => 'Sinhala, Sinhalese', 'es' => 'Cingalés']), 'status' => false],
                ['code' => 'sk', 'name' => json_encode(['en' => 'Slovak', 'es' => 'Eslovaco']), 'status' => false],
                ['code' => 'sl', 'name' => json_encode(['en' => 'Slovenian', 'es' => 'Esloveno']), 'status' => false],
                ['code' => 'so', 'name' => json_encode(['en' => 'Somali', 'es' => 'Somalí']), 'status' => false],
                ['code' => 'st', 'name' => json_encode(['en' => 'Southern Sotho', 'es' => 'Sotho del sur']), 'status' => false],
                ['code' => 'es', 'name' => json_encode(['en' => 'Spanish, Castilian', 'es' => 'Español, Castellano']), 'status' => true],
                ['code' => 'su', 'name' => json_encode(['en' => 'Sundanese', 'es' => 'Sundanés']), 'status' => false],
                ['code' => 'sw', 'name' => json_encode(['en' => 'Swahili', 'es' => 'Swahili']), 'status' => false],
                ['code' => 'ss', 'name' => json_encode(['en' => 'Swati', 'es' => 'Swati']), 'status' => false],
                ['code' => 'sv', 'name' => json_encode(['en' => 'Swedish', 'es' => 'Sueco']), 'status' => false],
                ['code' => 'ta', 'name' => json_encode(['en' => 'Tamil', 'es' => 'Tamil']), 'status' => false],
                ['code' => 'te', 'name' => json_encode(['en' => 'Telugu', 'es' => 'Telugu']), 'status' => false],
                ['code' => 'tg', 'name' => json_encode(['en' => 'Tajik', 'es' => 'Tayiko']), 'status' => false],
                ['code' => 'th', 'name' => json_encode(['en' => 'Thai', 'es' => 'Tailandés']), 'status' => false],
                ['code' => 'ti', 'name' => json_encode(['en' => 'Tigrinya', 'es' => 'Tigrinya']), 'status' => false],
                ['code' => 'bo', 'name' => json_encode(['en' => 'Tibetan', 'es' => 'Tibetano']), 'status' => false],
                ['code' => 'tk', 'name' => json_encode(['en' => 'Turkmen', 'es' => 'Turkmeno']), 'status' => false],
                ['code' => 'tl', 'name' => json_encode(['en' => 'Tagalog', 'es' => 'Tagalo']), 'status' => false],
                ['code' => 'tn', 'name' => json_encode(['en' => 'Tswana', 'es' => 'Tswana']), 'status' => false],
                ['code' => 'to', 'name' => json_encode(['en' => 'Tonga (Tonga Islands)', 'es' => 'Tonga (Islas Tonga)']), 'status' => false],
                ['code' => 'tr', 'name' => json_encode(['en' => 'Turkish', 'es' => 'Turco']), 'status' => false],
                ['code' => 'ts', 'name' => json_encode(['en' => 'Tsonga', 'es' => 'Tsonga']), 'status' => false],
                ['code' => 'tt', 'name' => json_encode(['en' => 'Tatar', 'es' => 'Tártaro']), 'status' => false],
                ['code' => 'tw', 'name' => json_encode(['en' => 'Twi', 'es' => 'Twi']), 'status' => false],
                ['code' => 'ty', 'name' => json_encode(['en' => 'Tahitian', 'es' => 'Tahitiano']), 'status' => false],
                ['code' => 'ug', 'name' => json_encode(['en' => 'Uighur, Uyghur', 'es' => 'Uigures']), 'status' => false],
                ['code' => 'uk', 'name' => json_encode(['en' => 'Ukrainian', 'es' => 'Ucraniano']), 'status' => false],
                ['code' => 'ur', 'name' => json_encode(['en' => 'Urdu', 'es' => 'Urdu']), 'status' => false],
                ['code' => 'uz', 'name' => json_encode(['en' => 'Uzbek', 'es' => 'Uzbeco']), 'status' => false],
                ['code' => 've', 'name' => json_encode(['en' => 'Venda', 'es' => 'Venda']), 'status' => false],
                ['code' => 'vi', 'name' => json_encode(['en' => 'Vietnamese', 'es' => 'Vietnamita']), 'status' => false],
                ['code' => 'vo', 'name' => json_encode(['en' => 'Volapük', 'es' => 'Volapük']), 'status' => false],
                ['code' => 'wa', 'name' => json_encode(['en' => 'Walloon', 'es' => 'Valón']), 'status' => false],
                ['code' => 'cy', 'name' => json_encode(['en' => 'Welsh', 'es' => 'Galés']), 'status' => false],
                ['code' => 'wo', 'name' => json_encode(['en' => 'Wolof', 'es' => 'Wolof']), 'status' => false],
                ['code' => 'fy', 'name' => json_encode(['en' => 'Western Frisian', 'es' => 'Frisón Occidental']), 'status' => false],
                ['code' => 'xh', 'name' => json_encode(['en' => 'Xhosa', 'es' => 'Xhosa']), 'status' => false],
                ['code' => 'yi', 'name' => json_encode(['en' => 'Yiddish', 'es' => 'Yídish']), 'status' => false],
                ['code' => 'yo', 'name' => json_encode(['en' => 'Yoruba', 'es' => 'Yoruba']), 'status' => false],
                ['code' => 'za', 'name' => json_encode(['en' => 'Zhuang, Chuang', 'es' => 'Zhuang, Chuang']), 'status' => false],
                ['code' => 'zu', 'name' => json_encode(['en' => 'Zulu', 'es' => 'Zulú']), 'status' => false],
            ], ['code'], ['name', 'status']);
        }
    }
}
