<?php

namespace Anibalealvarezs\Projectbuilder\Database\Seeders;

use Anibalealvarezs\Projectbuilder\Models\PbLanguage as Language;
use Illuminate\Database\Seeder;

class PbLanguagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Default Languages
        Language::create(['name' => 'Abkhazian', 'code' => 'ab']);
        Language::create(['name' => 'Afar', 'code' => 'aa']);
        Language::create(['name' => 'Afrikaans', 'code' => 'af']);
        Language::create(['name' => 'Akan', 'code' => 'ak']);
        Language::create(['name' => 'Albanian', 'code' => 'sq']);
        Language::create(['name' => 'Amharic', 'code' => 'am']);
        Language::create(['name' => 'Arabic', 'code' => 'ar']);
        Language::create(['name' => 'Aragonese', 'code' => 'an']);
        Language::create(['name' => 'Armenian', 'code' => 'hy']);
        Language::create(['name' => 'Assamese', 'code' => 'as']);
        Language::create(['name' => 'Avaric', 'code' => 'av']);
        Language::create(['name' => 'Avestan', 'code' => 'ae']);
        Language::create(['name' => 'Aymara', 'code' => 'ay']);
        Language::create(['name' => 'Azerbaijani', 'code' => 'az']);
        Language::create(['name' => 'Bambara', 'code' => 'bm']);
        Language::create(['name' => 'Bashkir', 'code' => 'ba']);
        Language::create(['name' => 'Basque', 'code' => 'eu']);
        Language::create(['name' => 'Belarusian', 'code' => 'be']);
        Language::create(['name' => 'Bengali', 'code' => 'bn']);
        Language::create(['name' => 'Bihari languages', 'code' => 'bh']);
        Language::create(['name' => 'Bislama', 'code' => 'bi']);
        Language::create(['name' => 'Bosnian', 'code' => 'bs']);
        Language::create(['name' => 'Breton', 'code' => 'br']);
        Language::create(['name' => 'Bulgarian', 'code' => 'bg']);
        Language::create(['name' => 'Burmese', 'code' => 'my']);
        Language::create(['name' => 'Catalan, Valencian', 'code' => 'ca']);
        Language::create(['name' => 'Chamorro', 'code' => 'ch']);
        Language::create(['name' => 'Chechen', 'code' => 'ce']);
        Language::create(['name' => 'Chichewa, Chewa, Nyanja', 'code' => 'ny']);
        Language::create(['name' => 'Chinese', 'code' => 'zh']);
        Language::create(['name' => 'Chuvash', 'code' => 'cv']);
        Language::create(['name' => 'Cornish', 'code' => 'kw']);
        Language::create(['name' => 'Corsican', 'code' => 'co']);
        Language::create(['name' => 'Cree', 'code' => 'cr']);
        Language::create(['name' => 'Croatian', 'code' => 'hr']);
        Language::create(['name' => 'Czech', 'code' => 'cs']);
        Language::create(['name' => 'Danish', 'code' => 'da']);
        Language::create(['name' => 'Divehi, Dhivehi, Maldivian', 'code' => 'dv']);
        Language::create(['name' => 'Dutch, Flemish', 'code' => 'nl']);
        Language::create(['name' => 'Dzongkha', 'code' => 'dz']);
        Language::create(['name' => 'English', 'code' => 'en', 'status' => 1]);
        Language::create(['name' => 'Esperanto', 'code' => 'eo']);
        Language::create(['name' => 'Estonian', 'code' => 'et']);
        Language::create(['name' => 'Ewe', 'code' => 'ee']);
        Language::create(['name' => 'Faroese', 'code' => 'fo']);
        Language::create(['name' => 'Fijian', 'code' => 'fj']);
        Language::create(['name' => 'Finnish', 'code' => 'fi']);
        Language::create(['name' => 'French', 'code' => 'fr']);
        Language::create(['name' => 'Fulah', 'code' => 'ff']);
        Language::create(['name' => 'Galician', 'code' => 'gl']);
        Language::create(['name' => 'Georgian', 'code' => 'ka']);
        Language::create(['name' => 'German', 'code' => 'de']);
        Language::create(['name' => 'Greek (modern)', 'code' => 'el']);
        Language::create(['name' => 'Guaraní', 'code' => 'gn']);
        Language::create(['name' => 'Gujarati', 'code' => 'gu']);
        Language::create(['name' => 'Haitian, Haitian Creole', 'code' => 'ht']);
        Language::create(['name' => 'Hausa', 'code' => 'ha']);
        Language::create(['name' => 'Hebrew (modern)', 'code' => 'he']);
        Language::create(['name' => 'Herero', 'code' => 'hz']);
        Language::create(['name' => 'Hindi', 'code' => 'hi']);
        Language::create(['name' => 'Hiri Motu', 'code' => 'ho']);
        Language::create(['name' => 'Hungarian', 'code' => 'hu']);
        Language::create(['name' => 'Interlingua', 'code' => 'ia']);
        Language::create(['name' => 'Indonesian', 'code' => 'id']);
        Language::create(['name' => 'Interlingue', 'code' => 'ie']);
        Language::create(['name' => 'Irish', 'code' => 'ga']);
        Language::create(['name' => 'Igbo', 'code' => 'ig']);
        Language::create(['name' => 'Inupiaq', 'code' => 'ik']);
        Language::create(['name' => 'Ido', 'code' => 'io']);
        Language::create(['name' => 'Icelandic', 'code' => 'is']);
        Language::create(['name' => 'Italian', 'code' => 'it']);
        Language::create(['name' => 'Inuktitut', 'code' => 'iu']);
        Language::create(['name' => 'Japanese', 'code' => 'ja']);
        Language::create(['name' => 'Javanese', 'code' => 'jv']);
        Language::create(['name' => 'Kalaallisut, Greenlandic', 'code' => 'kl']);
        Language::create(['name' => 'Kannada', 'code' => 'kn']);
        Language::create(['name' => 'Kanuri', 'code' => 'kr']);
        Language::create(['name' => 'Kashmiri', 'code' => 'ks']);
        Language::create(['name' => 'Kazakh', 'code' => 'kk']);
        Language::create(['name' => 'Central Khmer', 'code' => 'km']);
        Language::create(['name' => 'Kikuyu, Gikuyu', 'code' => 'ki']);
        Language::create(['name' => 'Kinyarwanda', 'code' => 'rw']);
        Language::create(['name' => 'Kirghiz, Kyrgyz', 'code' => 'ky']);
        Language::create(['name' => 'Komi', 'code' => 'kv']);
        Language::create(['name' => 'Kongo', 'code' => 'kg']);
        Language::create(['name' => 'Korean', 'code' => 'ko']);
        Language::create(['name' => 'Kurdish', 'code' => 'ku']);
        Language::create(['name' => 'Kuanyama, Kwanyama', 'code' => 'kj']);
        Language::create(['name' => 'Latin', 'code' => 'la']);
        Language::create(['name' => 'Luxembourgish, Letzeburgesch', 'code' => 'lb']);
        Language::create(['name' => 'Ganda', 'code' => 'lg']);
        Language::create(['name' => 'Limburgan, Limburger, Limburgish', 'code' => 'li']);
        Language::create(['name' => 'Lingala', 'code' => 'ln']);
        Language::create(['name' => 'Lao', 'code' => 'lo']);
        Language::create(['name' => 'Lithuanian', 'code' => 'lt']);
        Language::create(['name' => 'Luba-Katanga', 'code' => 'lu']);
        Language::create(['name' => 'Latvian', 'code' => 'lv']);
        Language::create(['name' => 'Manx', 'code' => 'gv']);
        Language::create(['name' => 'Macedonian', 'code' => 'mk']);
        Language::create(['name' => 'Malagasy', 'code' => 'mg']);
        Language::create(['name' => 'Malay', 'code' => 'ms']);
        Language::create(['name' => 'Malayalam', 'code' => 'ml']);
        Language::create(['name' => 'Maltese', 'code' => 'mt']);
        Language::create(['name' => 'Maori', 'code' => 'mi']);
        Language::create(['name' => 'Marathi', 'code' => 'mr']);
        Language::create(['name' => 'Marshallese', 'code' => 'mh']);
        Language::create(['name' => 'Mongolian', 'code' => 'mn']);
        Language::create(['name' => 'Nauru', 'code' => 'na']);
        Language::create(['name' => 'Navajo, Navaho', 'code' => 'nv']);
        Language::create(['name' => 'North Ndebele', 'code' => 'nd']);
        Language::create(['name' => 'Nepali', 'code' => 'ne']);
        Language::create(['name' => 'Ndonga', 'code' => 'ng']);
        Language::create(['name' => 'Norwegian Bokmål', 'code' => 'nb']);
        Language::create(['name' => 'Norwegian Nynorsk', 'code' => 'nn']);
        Language::create(['name' => 'Norwegian', 'code' => 'no']);
        Language::create(['name' => 'Sichuan Yi, Nuosu', 'code' => 'ii']);
        Language::create(['name' => 'South Ndebele', 'code' => 'nr']);
        Language::create(['name' => 'Occitan', 'code' => 'oc']);
        Language::create(['name' => 'Ojibwa', 'code' => 'oj']);
        Language::create(['name' => 'Church Slavic, Church Slavonic, Old Church Slavonic, Old Slavonic, Old Bulgarian', 'code' => 'cu']);
        Language::create(['name' => 'Oromo', 'code' => 'om']);
        Language::create(['name' => 'Oriya', 'code' => 'or']);
        Language::create(['name' => 'Ossetian, Ossetic', 'code' => 'os']);
        Language::create(['name' => 'Panjabi, Punjabi', 'code' => 'pa']);
        Language::create(['name' => 'Pali', 'code' => 'pi']);
        Language::create(['name' => 'Persian', 'code' => 'fa']);
        Language::create(['name' => 'Polabian', 'code' => 'po']);
        Language::create(['name' => 'Polish', 'code' => 'pl']);
        Language::create(['name' => 'Pashto, Pushto', 'code' => 'ps']);
        Language::create(['name' => 'Portuguese', 'code' => 'pt']);
        Language::create(['name' => 'Quechua', 'code' => 'qu']);
        Language::create(['name' => 'Romansh', 'code' => 'rm']);
        Language::create(['name' => 'Rundi', 'code' => 'rn']);
        Language::create(['name' => 'Romanian, Moldavian, Moldovan', 'code' => 'ro']);
        Language::create(['name' => 'Russian', 'code' => 'ru']);
        Language::create(['name' => 'Sanskrit', 'code' => 'sa']);
        Language::create(['name' => 'Sardinian', 'code' => 'sc']);
        Language::create(['name' => 'Sindhi', 'code' => 'sd']);
        Language::create(['name' => 'Northern Sami', 'code' => 'se']);
        Language::create(['name' => 'Samoan', 'code' => 'sm']);
        Language::create(['name' => 'Sango', 'code' => 'sg']);
        Language::create(['name' => 'Serbian', 'code' => 'sr']);
        Language::create(['name' => 'Gaelic, Scottish Gaelic', 'code' => 'gd']);
        Language::create(['name' => 'Shona', 'code' => 'sn']);
        Language::create(['name' => 'Sinhala, Sinhalese', 'code' => 'si']);
        Language::create(['name' => 'Slovak', 'code' => 'sk']);
        Language::create(['name' => 'Slovenian', 'code' => 'sl']);
        Language::create(['name' => 'Somali', 'code' => 'so']);
        Language::create(['name' => 'Southern Sotho', 'code' => 'st']);
        Language::create(['name' => 'Spanish, Castilian', 'code' => 'es', 'status' => 1]);
        Language::create(['name' => 'Sundanese', 'code' => 'su']);
        Language::create(['name' => 'Swahili', 'code' => 'sw']);
        Language::create(['name' => 'Swati', 'code' => 'ss']);
        Language::create(['name' => 'Swedish', 'code' => 'sv']);
        Language::create(['name' => 'Tamil', 'code' => 'ta']);
        Language::create(['name' => 'Telugu', 'code' => 'te']);
        Language::create(['name' => 'Tajik', 'code' => 'tg']);
        Language::create(['name' => 'Thai', 'code' => 'th']);
        Language::create(['name' => 'Tigrinya', 'code' => 'ti']);
        Language::create(['name' => 'Tibetan', 'code' => 'bo']);
        Language::create(['name' => 'Turkmen', 'code' => 'tk']);
        Language::create(['name' => 'Tagalog', 'code' => 'tl']);
        Language::create(['name' => 'Tswana', 'code' => 'tn']);
        Language::create(['name' => 'Tonga (Tonga Islands)', 'code' => 'to']);
        Language::create(['name' => 'Turkish', 'code' => 'tr']);
        Language::create(['name' => 'Tsonga', 'code' => 'ts']);
        Language::create(['name' => 'Tatar', 'code' => 'tt']);
        Language::create(['name' => 'Twi', 'code' => 'tw']);
        Language::create(['name' => 'Tahitian', 'code' => 'ty']);
        Language::create(['name' => 'Uighur, Uyghur', 'code' => 'ug']);
        Language::create(['name' => 'Ukrainian', 'code' => 'uk']);
        Language::create(['name' => 'Urdu', 'code' => 'ur']);
        Language::create(['name' => 'Uzbek', 'code' => 'uz']);
        Language::create(['name' => 'Venda', 'code' => 've']);
        Language::create(['name' => 'Vietnamese', 'code' => 'vi']);
        Language::create(['name' => 'Volapük', 'code' => 'vo']);
        Language::create(['name' => 'Walloon', 'code' => 'wa']);
        Language::create(['name' => 'Welsh', 'code' => 'cy']);
        Language::create(['name' => 'Wolof', 'code' => 'wo']);
        Language::create(['name' => 'Western Frisian', 'code' => 'fy']);
        Language::create(['name' => 'Xhosa', 'code' => 'xh']);
        Language::create(['name' => 'Yiddish', 'code' => 'yi']);
        Language::create(['name' => 'Yoruba', 'code' => 'yo']);
        Language::create(['name' => 'Zhuang, Chuang', 'code' => 'za']);
        Language::create(['name' => 'Zulu', 'code' => 'zu']);
    }
}
