<?php

namespace Anibalealvarezs\Projectbuilder\Database\Seeders;

use Anibalealvarezs\Projectbuilder\Models\PbLanguage as Language;
use Illuminate\Database\Seeder;

class PbLanguagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (Language::count() == 0) {
            // Default Languages
            Language::upsert([
                ['code' => 'ab', 'name' => 'Abkhazian', 'status' => false],
                ['code' => 'aa', 'name' => 'Afar', 'status' => false],
                ['code' => 'af', 'name' => 'Afrikaans', 'status' => false],
                ['code' => 'ak', 'name' => 'Akan', 'status' => false],
                ['code' => 'sq', 'name' => 'Albanian', 'status' => false],
                ['code' => 'am', 'name' => 'Amharic', 'status' => false],
                ['code' => 'ar', 'name' => 'Arabic', 'status' => false],
                ['code' => 'an', 'name' => 'Aragonese', 'status' => false],
                ['code' => 'hy', 'name' => 'Armenian', 'status' => false],
                ['code' => 'as', 'name' => 'Assamese', 'status' => false],
                ['code' => 'av', 'name' => 'Avaric', 'status' => false],
                ['code' => 'ae', 'name' => 'Avestan', 'status' => false],
                ['code' => 'ay', 'name' => 'Aymara', 'status' => false],
                ['code' => 'az', 'name' => 'Azerbaijani', 'status' => false],
                ['code' => 'bm', 'name' => 'Bambara', 'status' => false],
                ['code' => 'ba', 'name' => 'Bashkir', 'status' => false],
                ['code' => 'eu', 'name' => 'Basque', 'status' => false],
                ['code' => 'be', 'name' => 'Belarusian', 'status' => false],
                ['code' => 'bn', 'name' => 'Bengali', 'status' => false],
                ['code' => 'bh', 'name' => 'Bihari languages', 'status' => false],
                ['code' => 'bi', 'name' => 'Bislama', 'status' => false],
                ['code' => 'bs', 'name' => 'Bosnian', 'status' => false],
                ['code' => 'br', 'name' => 'Breton', 'status' => false],
                ['code' => 'bg', 'name' => 'Bulgarian', 'status' => false],
                ['code' => 'my', 'name' => 'Burmese', 'status' => false],
                ['code' => 'ca', 'name' => 'Catalan, Valencian', 'status' => false],
                ['code' => 'ch', 'name' => 'Chamorro', 'status' => false],
                ['code' => 'ce', 'name' => 'Chechen', 'status' => false],
                ['code' => 'ny', 'name' => 'Chichewa, Chewa, Nyanja', 'status' => false],
                ['code' => 'zh', 'name' => 'Chinese', 'status' => false],
                ['code' => 'cv', 'name' => 'Chuvash', 'status' => false],
                ['code' => 'kw', 'name' => 'Cornish', 'status' => false],
                ['code' => 'co', 'name' => 'Corsican', 'status' => false],
                ['code' => 'cr', 'name' => 'Cree', 'status' => false],
                ['code' => 'hr', 'name' => 'Croatian', 'status' => false],
                ['code' => 'cs', 'name' => 'Czech', 'status' => false],
                ['code' => 'da', 'name' => 'Danish', 'status' => false],
                ['code' => 'dv', 'name' => 'Divehi, Dhivehi, Maldivian', 'status' => false],
                ['code' => 'nl', 'name' => 'Dutch, Flemish', 'status' => false],
                ['code' => 'dz', 'name' => 'Dzongkha', 'status' => false],
                ['code' => 'en', 'name' => 'English', 'status' => true],
                ['code' => 'eo', 'name' => 'Esperanto', 'status' => false],
                ['code' => 'et', 'name' => 'Estonian', 'status' => false],
                ['code' => 'ee', 'name' => 'Ewe', 'status' => false],
                ['code' => 'fo', 'name' => 'Faroese', 'status' => false],
                ['code' => 'fj', 'name' => 'Fijian', 'status' => false],
                ['code' => 'fi', 'name' => 'Finnish', 'status' => false],
                ['code' => 'fr', 'name' => 'French', 'status' => false],
                ['code' => 'ff', 'name' => 'Fulah', 'status' => false],
                ['code' => 'gl', 'name' => 'Galician', 'status' => false],
                ['code' => 'ka', 'name' => 'Georgian', 'status' => false],
                ['code' => 'de', 'name' => 'German', 'status' => false],
                ['code' => 'el', 'name' => 'Greek (modern)', 'status' => false],
                ['code' => 'gn', 'name' => 'Guaraní', 'status' => false],
                ['code' => 'gu', 'name' => 'Gujarati', 'status' => false],
                ['code' => 'ht', 'name' => 'Haitian, Haitian Creole', 'status' => false],
                ['code' => 'ha', 'name' => 'Hausa', 'status' => false],
                ['code' => 'he', 'name' => 'Hebrew (modern)', 'status' => false],
                ['code' => 'hz', 'name' => 'Herero', 'status' => false],
                ['code' => 'hi', 'name' => 'Hindi', 'status' => false],
                ['code' => 'ho', 'name' => 'Hiri Motu', 'status' => false],
                ['code' => 'hu', 'name' => 'Hungarian', 'status' => false],
                ['code' => 'ia', 'name' => 'Interlingua', 'status' => false],
                ['code' => 'id', 'name' => 'Indonesian', 'status' => false],
                ['code' => 'ie', 'name' => 'Interlingue', 'status' => false],
                ['code' => 'ga', 'name' => 'Irish', 'status' => false],
                ['code' => 'ig', 'name' => 'Igbo', 'status' => false],
                ['code' => 'ik', 'name' => 'Inupiaq', 'status' => false],
                ['code' => 'io', 'name' => 'Ido', 'status' => false],
                ['code' => 'is', 'name' => 'Icelandic', 'status' => false],
                ['code' => 'it', 'name' => 'Italian', 'status' => false],
                ['code' => 'iu', 'name' => 'Inuktitut', 'status' => false],
                ['code' => 'ja', 'name' => 'Japanese', 'status' => false],
                ['code' => 'jv', 'name' => 'Javanese', 'status' => false],
                ['code' => 'kl', 'name' => 'Kalaallisut, Greenlandic', 'status' => false],
                ['code' => 'kn', 'name' => 'Kannada', 'status' => false],
                ['code' => 'kr', 'name' => 'Kanuri', 'status' => false],
                ['code' => 'ks', 'name' => 'Kashmiri', 'status' => false],
                ['code' => 'kk', 'name' => 'Kazakh', 'status' => false],
                ['code' => 'km', 'name' => 'Central Khmer', 'status' => false],
                ['code' => 'ki', 'name' => 'Kikuyu, Gikuyu', 'status' => false],
                ['code' => 'rw', 'name' => 'Kinyarwanda', 'status' => false],
                ['code' => 'ky', 'name' => 'Kirghiz, Kyrgyz', 'status' => false],
                ['code' => 'kv', 'name' => 'Komi', 'status' => false],
                ['code' => 'kg', 'name' => 'Kongo', 'status' => false],
                ['code' => 'ko', 'name' => 'Korean', 'status' => false],
                ['code' => 'ku', 'name' => 'Kurdish', 'status' => false],
                ['code' => 'kj', 'name' => 'Kuanyama, Kwanyama', 'status' => false],
                ['code' => 'la', 'name' => 'Latin', 'status' => false],
                ['code' => 'lb', 'name' => 'Luxembourgish, Letzeburgesch', 'status' => false],
                ['code' => 'lg', 'name' => 'Ganda', 'status' => false],
                ['code' => 'li', 'name' => 'Limburgan, Limburger, Limburgish', 'status' => false],
                ['code' => 'ln', 'name' => 'Lingala', 'status' => false],
                ['code' => 'lo', 'name' => 'Lao', 'status' => false],
                ['code' => 'lt', 'name' => 'Lithuanian', 'status' => false],
                ['code' => 'lu', 'name' => 'Luba-Katanga', 'status' => false],
                ['code' => 'lv', 'name' => 'Latvian', 'status' => false],
                ['code' => 'gv', 'name' => 'Manx', 'status' => false],
                ['code' => 'mk', 'name' => 'Macedonian', 'status' => false],
                ['code' => 'mg', 'name' => 'Malagasy', 'status' => false],
                ['code' => 'ms', 'name' => 'Malay', 'status' => false],
                ['code' => 'ml', 'name' => 'Malayalam', 'status' => false],
                ['code' => 'mt', 'name' => 'Maltese', 'status' => false],
                ['code' => 'mi', 'name' => 'Maori', 'status' => false],
                ['code' => 'mr', 'name' => 'Marathi', 'status' => false],
                ['code' => 'mh', 'name' => 'Marshallese', 'status' => false],
                ['code' => 'mn', 'name' => 'Mongolian', 'status' => false],
                ['code' => 'na', 'name' => 'Nauru', 'status' => false],
                ['code' => 'nv', 'name' => 'Navajo, Navaho', 'status' => false],
                ['code' => 'nd', 'name' => 'North Ndebele', 'status' => false],
                ['code' => 'ne', 'name' => 'Nepali', 'status' => false],
                ['code' => 'ng', 'name' => 'Ndonga', 'status' => false],
                ['code' => 'nb', 'name' => 'Norwegian Bokmål', 'status' => false],
                ['code' => 'nn', 'name' => 'Norwegian Nynorsk', 'status' => false],
                ['code' => 'no', 'name' => 'Norwegian', 'status' => false],
                ['code' => 'ii', 'name' => 'Sichuan Yi, Nuosu', 'status' => false],
                ['code' => 'nr', 'name' => 'South Ndebele', 'status' => false],
                ['code' => 'oc', 'name' => 'Occitan', 'status' => false],
                ['code' => 'oj', 'name' => 'Ojibwa', 'status' => false],
                ['code' => 'cu', 'name' => 'Church Slavic, Church Slavonic, Old Church Slavonic, Old Slavonic, Old Bulgarian', 'status' => false],
                ['code' => 'om', 'name' => 'Oromo', 'status' => false],
                ['code' => 'or', 'name' => 'Oriya', 'status' => false],
                ['code' => 'os', 'name' => 'Ossetian, Ossetic', 'status' => false],
                ['code' => 'pa', 'name' => 'Panjabi, Punjabi', 'status' => false],
                ['code' => 'pi', 'name' => 'Pali', 'status' => false],
                ['code' => 'fa', 'name' => 'Persian', 'status' => false],
                ['code' => 'po', 'name' => 'Polabian', 'status' => false],
                ['code' => 'pl', 'name' => 'Polish', 'status' => false],
                ['code' => 'ps', 'name' => 'Pashto, Pushto', 'status' => false],
                ['code' => 'pt', 'name' => 'Portuguese', 'status' => false],
                ['code' => 'qu', 'name' => 'Quechua', 'status' => false],
                ['code' => 'rm', 'name' => 'Romansh', 'status' => false],
                ['code' => 'rn', 'name' => 'Rundi', 'status' => false],
                ['code' => 'ro', 'name' => 'Romanian, Moldavian, Moldovan', 'status' => false],
                ['code' => 'ru', 'name' => 'Russian', 'status' => false],
                ['code' => 'sa', 'name' => 'Sanskrit', 'status' => false],
                ['code' => 'sc', 'name' => 'Sardinian', 'status' => false],
                ['code' => 'sd', 'name' => 'Sindhi', 'status' => false],
                ['code' => 'se', 'name' => 'Northern Sami', 'status' => false],
                ['code' => 'sm', 'name' => 'Samoan', 'status' => false],
                ['code' => 'sg', 'name' => 'Sango', 'status' => false],
                ['code' => 'sr', 'name' => 'Serbian', 'status' => false],
                ['code' => 'gd', 'name' => 'Gaelic, Scottish Gaelic', 'status' => false],
                ['code' => 'sn', 'name' => 'Shona', 'status' => false],
                ['code' => 'si', 'name' => 'Sinhala, Sinhalese', 'status' => false],
                ['code' => 'sk', 'name' => 'Slovak', 'status' => false],
                ['code' => 'sl', 'name' => 'Slovenian', 'status' => false],
                ['code' => 'so', 'name' => 'Somali', 'status' => false],
                ['code' => 'st', 'name' => 'Southern Sotho', 'status' => false],
                ['code' => 'es', 'name' => 'Spanish, Castilian', 'status' => true],
                ['code' => 'su', 'name' => 'Sundanese', 'status' => false],
                ['code' => 'sw', 'name' => 'Swahili', 'status' => false],
                ['code' => 'ss', 'name' => 'Swati', 'status' => false],
                ['code' => 'sv', 'name' => 'Swedish', 'status' => false],
                ['code' => 'ta', 'name' => 'Tamil', 'status' => false],
                ['code' => 'te', 'name' => 'Telugu', 'status' => false],
                ['code' => 'tg', 'name' => 'Tajik', 'status' => false],
                ['code' => 'th', 'name' => 'Thai', 'status' => false],
                ['code' => 'ti', 'name' => 'Tigrinya', 'status' => false],
                ['code' => 'bo', 'name' => 'Tibetan', 'status' => false],
                ['code' => 'tk', 'name' => 'Turkmen', 'status' => false],
                ['code' => 'tl', 'name' => 'Tagalog', 'status' => false],
                ['code' => 'tn', 'name' => 'Tswana', 'status' => false],
                ['code' => 'to', 'name' => 'Tonga (Tonga Islands)', 'status' => false],
                ['code' => 'tr', 'name' => 'Turkish', 'status' => false],
                ['code' => 'ts', 'name' => 'Tsonga', 'status' => false],
                ['code' => 'tt', 'name' => 'Tatar', 'status' => false],
                ['code' => 'tw', 'name' => 'Twi', 'status' => false],
                ['code' => 'ty', 'name' => 'Tahitian', 'status' => false],
                ['code' => 'ug', 'name' => 'Uighur, Uyghur', 'status' => false],
                ['code' => 'uk', 'name' => 'Ukrainian', 'status' => false],
                ['code' => 'ur', 'name' => 'Urdu', 'status' => false],
                ['code' => 'uz', 'name' => 'Uzbek', 'status' => false],
                ['code' => 've', 'name' => 'Venda', 'status' => false],
                ['code' => 'vi', 'name' => 'Vietnamese', 'status' => false],
                ['code' => 'vo', 'name' => 'Volapük', 'status' => false],
                ['code' => 'wa', 'name' => 'Walloon', 'status' => false],
                ['code' => 'cy', 'name' => 'Welsh', 'status' => false],
                ['code' => 'wo', 'name' => 'Wolof', 'status' => false],
                ['code' => 'fy', 'name' => 'Western Frisian', 'status' => false],
                ['code' => 'xh', 'name' => 'Xhosa', 'status' => false],
                ['code' => 'yi', 'name' => 'Yiddish', 'status' => false],
                ['code' => 'yo', 'name' => 'Yoruba', 'status' => false],
                ['code' => 'za', 'name' => 'Zhuang, Chuang', 'status' => false],
                ['code' => 'zu', 'name' => 'Zulu', 'status' => false],
            ], ['code'], ['name', 'status']);
        }
    }
}
